In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
from admin import POSTGRES_PASS
from alpaca_api import get_news
from transformers import pipeline
import torch

C:\Users\kiera\miniconda3\envs\diss-notebook\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
connection = f'postgresql+psycopg2://postgres:{POSTGRES_PASS}@localhost:5432/stock_market'

db_engine = create_engine(connection)
query = "SELECT * FROM stock_prices"
query2 = "SELECT * FROM futures_prices"

In [3]:
with db_engine.connect() as conn:
    stocks_result = conn.execute(text(query))
    futures_result = conn.execute(text(query2))
    
    stocks_rows = stocks_result.fetchall()
    stocks_column = stocks_result.keys()

    futures_rows = futures_result.fetchall()
    futures_column = futures_result.keys()
    

stocks_df = pd.DataFrame(stocks_rows, columns=stocks_column)
futures_df = pd.DataFrame(futures_rows, columns=futures_column)

In [4]:
pd.set_option('display.max_colwidth', None)

In [5]:
stocks_df.head()

,Datetime,Open,High,Low,Close,Volume,Dividends,Stock Splits,ticker,Capital Gains
0,2026-02-10 14:30:00+00:00,191.404999,192.429993,191.250000,191.654999,4043021,0.0,0.0,NVDA,NaN
1,2026-02-10 14:31:00+00:00,191.610001,192.139999,191.080002,192.119995,781651,0.0,0.0,NVDA,NaN
2,2026-02-10 14:32:00+00:00,192.139999,192.479996,191.323593,191.460007,778435,0.0,0.0,NVDA,NaN
3,2026-02-10 14:33:00+00:00,191.465897,191.490005,190.740097,190.919998,575746,0.0,0.0,NVDA,NaN
4,2026-02-10 14:34:00+00:00,190.910004,191.279999,190.610001,190.824997,524921,0.0,0.0,NVDA,NaN

In [6]:
futures_df.head()

,Datetime,ticker,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2026-02-10 05:00:00+00:00,GC=F,5052.89990234375,5057.39990234375,5051.7001953125,5055.39990234375,None,0,0.0,0.0
1,2026-02-10 05:01:00+00:00,GC=F,5055.0,5055.0,5053.2998046875,5053.7998046875,None,4,0.0,0.0
2,2026-02-10 05:02:00+00:00,GC=F,5052.39990234375,5052.39990234375,5052.39990234375,5052.39990234375,None,1,0.0,0.0
3,2026-02-10 05:03:00+00:00,GC=F,5052.2001953125,5053.39990234375,5051.89990234375,5053.39990234375,None,9,0.0,0.0
4,2026-02-10 05:04:00+00:00,GC=F,5054.0,5054.60009765625,5053.5,5053.60009765625,None,8,0.0,0.0

In [7]:
dates = set(pd.to_datetime(stocks_df["Datetime"]).dt.date)
dates

{datetime.date(2026, 2, 10),
 datetime.date(2026, 2, 12),
 datetime.date(2026, 2, 13),
 datetime.date(2026, 2, 17),
 datetime.date(2026, 2, 18),
 datetime.date(2026, 2, 19),
 datetime.date(2026, 2, 20),
 datetime.date(2026, 2, 23),
 datetime.date(2026, 2, 24),
 datetime.date(2026, 2, 25),
 datetime.date(2026, 2, 26),
 datetime.date(2026, 2, 27),
 datetime.date(2026, 3, 2),
 datetime.date(2026, 3, 3),
 datetime.date(2026, 3, 4),
 datetime.date(2026, 3, 5),
 datetime.date(2026, 3, 6)}

In [8]:
dates = set(pd.to_datetime(futures_df["Datetime"]).dt.date)
dates

{datetime.date(2026, 2, 10),
 datetime.date(2026, 2, 11),
 datetime.date(2026, 2, 12),
 datetime.date(2026, 2, 13),
 datetime.date(2026, 2, 15),
 datetime.date(2026, 2, 16),
 datetime.date(2026, 2, 17),
 datetime.date(2026, 2, 18),
 datetime.date(2026, 2, 19),
 datetime.date(2026, 2, 20),
 datetime.date(2026, 2, 22),
 datetime.date(2026, 2, 23),
 datetime.date(2026, 2, 24),
 datetime.date(2026, 2, 25),
 datetime.date(2026, 2, 26),
 datetime.date(2026, 2, 27),
 datetime.date(2026, 3, 1),
 datetime.date(2026, 3, 2),
 datetime.date(2026, 3, 3),
 datetime.date(2026, 3, 4),
 datetime.date(2026, 3, 5),
 datetime.date(2026, 3, 6)}

In [9]:
news_df = get_news("NVDA", "2026-03-02", desired_timeframe_in_days=3)
news_df

,id,author,publish_time,headline,source,related_tickers,summary
0,51045029,The Arora Report,2026-03-04 18:15:16+00:00,Secret Iran Outreach And Trump's Promise Of Safe Shipping Saves Stock Market But Here's A Fly In The Ointment,benzinga,"[AAPL, AMZN, BTCUSD, EWY, GDX, GLD, GOOG, META, MSFT, NVDA, QQQ, SIL, SLV, SPY, TSLA, USO]",\n\n\n\nSecret Iran Outreach\n\n\n
1,51043378,Benzinga Insights,2026-03-04 17:35:12+00:00,10 Information Technology Stocks Whale Activity In Today's Session,benzinga,"[ADBE, AMD, ASML, AVGO, CRWD, INTC, MU, NVDA, PANW, PLTR]",
2,51038396,Daragh Thomas,2026-03-04 15:39:22+00:00,Broadcom Earnings Prediction Market Preview: Can Hock Tan Succeed Where Jensen Huang Failed?,benzinga,"[AMD, AVGO, GOOGL, META, NVDA]","Broadcom (AVGO) has beaten EPS estimates for 19 straight quarters, but NVIDIA&#39;s (NVDA) recent beat and drop raises questions on the importance of beating estimates."
3,51036108,Anusuya Lahiri,2026-03-04 15:00:28+00:00,"Nvidia Leads Chip Stock Rebound, Billionaire Investor Buys 1 Million Shares To Defy AI 'Bubble' Fears",benzinga,"[AMD, ARM, AVGO, INTC, MU, NVDA, ON, SMCI, SSNLF, STX, TSLA, TSM, WDC]",Semiconductor stocks like Nvidia (NVDA) and AMD are bouncing back Wednesday. Discover why billionaire Leo KoGuan is doubling down on AI with a massive share purchase and why experts say the recent sell-off was a &#34;nervous market&#34; overreaction.
4,51028040,Eva Mathew,2026-03-04 13:55:49+00:00,"Stock Market Today: S&P 500, Dow Futures Up As Oil Prices Fall For First Time Since Iran War Began— Broadcom, Abercrombie & Fitch In Focus (UPDATED)",benzinga,"[ANF, AVGO, BOX, BTCUSD, CRWD, NVDA, OKTA, QQQ, ROST, SPY]","(Editor’s note: The headline, lede, and prices of futures, commodities, ETFs and stocks were updated and the ADP February jobs data was added)"
5,51033236,Nabaparna Bhattacharya,2026-03-04 13:54:07+00:00,CoreWeave Lands Major AI Deal With Perplexity,benzinga,"[CRWV, NVDA]",CoreWeave (CRWV) jumps 5%+ premarket! Strategic Perplexity partnership fuels bullish momentum. Technical levels and price targets inside.
6,51031666,Benzinga Newsdesk,2026-03-04 13:03:48+00:00,VCI Global's V Gallant Subsidiary Introduces Nvidia-Powered AI GPU Computing Center In Malaysia,benzinga,"[NVDA, VCIG]",
7,50934100,Anusuya Lahiri,2026-02-27 16:23:08+00:00,Why Nvidia's Record Profits Weren't Enough: Chip Stocks Tumble As AI Hype Hits A Wall,benzinga,"[AAPL, AMD, AMZN, ARM, AVGO, CRM, CRWV, DELL, INTC, META, MU, NVDA, ON, SMCI, TSLA, TSM]","Even with a 73% revenue jump, Nvidia (NVDA) stock fell 5%, dragging AMD and Intel down with it. Discover why Wall Street is suddenly worried about AI profitability and how rising oil prices are adding to the market chaos on Friday."
8,51028281,Anusuya Lahiri,2026-03-04 10:41:55+00:00,Alibaba Shock: Qwen AI Tech Lead Junyang Lin Abruptly Steps Down,benzinga,"[BABA, NVDA]",Alibaba&#39;s Qwen AI loses a key technical leader as Junyang Lin steps down following the debut of the new Qwen 3.5 models.
9,51028105,Namrata Sen,2026-03-04 10:31:26+00:00,White House Debates Over Tencent's Gaming Stakes Ahead Of Trump-Xi Meeting: Report,benzinga,"[NVDA, TCEHY]","Ahead of a meeting between President Donald Trump and Chinese President Xi Jinping in April, the White House is reportedly considering whether to allow Chinese tech giant Tencent Holdings Ltd. (OTC:TCEHY) to maintain its stakes in major video game companies."
10,51019835,Daragh Thomas,2026-03-03 21:23:58+00:00,"Nvidia Has 'Never Been So Cheap,' Bernstein Analyst Says",benzinga,"[AAPL, GOOGL, NVDA]","Bernstein analyst Stacy Rasgon bullish on Nvidia (NVDA), citing cheap valuation relative to chip industry. Morgan Stanley agrees, but Eisman doubts downstream risk. Prediction markets favor Nvidia&#39;s potential as top company by 2026."
11,51012372,Anusuya Lahiri,2026-03-03 18:38:53+00:00,What Is Going On With Micron Stock On Tuesday?,benzinga,"[MU, NVDA, SOXQ]","Micron (MU) shares were caught in a broader chip selloff Tuesday, but analysts at UBS and Stifel aren&#39;t blinking. Discover why experts just hiked their forecasts and how Micron&#39;s new 256GB &#34;lightweight&#34; memory module is designed to power the next wave of Nvidia AI servers."
12,51010001,Anusuya Lahiri,2026-03-03 17:44:35+00:00,Taiwan Semiconductor's AI Breakthroughs Don't Calm Wall Street—Profits Are The Flashpoint,benzinga,"[ASML, AVGO, NVDA, SMCI, SOXQ, TSM]",TSM shares fell alongside the broader chip index Tuesday as investors weigh geopolitical tensions and high AI costs. Discover how partners like Nvidia and Broadcom are fighting back with new &#34;Sovereign AI&#34; tech to save on energy and hardware.
13,51009942,The Arora Report,2026-03-03 17:43:16+00:00,Unsustainable War Math - $20K Drones Vs. $4M Patriot Missiles; South Korean Rout Hammers US Stocks,benzinga,"[AAPL, AMZN, BTCUSD, EWY, GDX, GLD, GOOG, META, MSFT, MU, NVDA, QQQ, RTX, SIL, SLV, SMH, SNDK, SPY, SSNLF, TSLA, USO]",\n\n\n\nComplacent Investors\n\n\n
14,51009571,Benzinga Insights,2026-03-03 17:35:16+00:00,10 Information Technology Stocks With Whale Alerts In Today's Session,benzinga,"[AAPL, BMNR, CRCL, CRWD, IBM, MSTR, NOW, NVDA, PLTR, TSM]",
15,51009077,Vandana Singh,2026-03-03 17:19:59+00:00,Nvidia's Genomic Analysis Suite To Help Speed Up Residual Cancer Detection,benzinga,"[COHR, NVDA]",Droplet Biosciences uses lymph fluid and NVIDIA Parabricks to detect residual cancer faster and cut analysis time and costs.
16,51008941,Chris Katje,2026-03-03 17:16:29+00:00,"Broadcom Q1 Preview: Record Revenue Expected, But Stock Is Looking 'On the Ropes'",benzinga,"[AVGO, NVDA]",Broadcom typically beats analyst estimates for both revenue and earnings per share. Here are the figures and items to watch for Q1.
17,51006149,Piero Cingari,2026-03-03 16:14:16+00:00,The $600 Billion Tech Wipeout: These 10 Stocks Are Cracking As Energy Prices Surge,benzinga,"[AAPL, AMZN, AVGO, GOOGL, MU, NVDA, SOXX, TSLA, TSM]","More than $600 billion was wiped from global tech and semiconductor stocks as the Iran conflict sparked an oil surge, volatility spike and broad risk-off selloff led by AI chipmakers."
18,51005737,Chris Katje,2026-03-03 16:06:56+00:00,"EXCLUSIVE: Top 12 Most-Searched Tickers On Benzinga Pro In February — Where Do Tesla, Nvidia, Palantir Stocks Rank?",benzinga,"[AAPL, AMD, AMZN, APLD, BNAI, HIMS, INTC, META, MU, NVDA, PLTR, QQQ, SLV, SNDK, SPY, TSLA]",The 12 most-searched tickers on Benzinga Pro for the month of February and how the interest has changed from recent months.
19,51001972,Benzinga Insights,2026-03-03 15:00:54+00:00,Price Over Earnings Overview: NVIDIA,benzinga,[NVDA],
20,51001722,Benzinga Newsdesk,2026-03-03 14:57:56+00:00,"Wedbush Maintains Outperform on NVIDIA, Raises Price Target to $300",benzinga,[NVDA],
21,50992878,Rishabh Mishra,2026-03-03 13:33:15+00:00,"Stock Market Today: Dow, S&P 500, Nasdaq Futures Plunge After Iran Shuts Strait Of Hormuz— Coherent, Credo, CrowdStrike In Focus (UPDATED)",benzinga,"[ASAN, BTCUSD, CALM, COHR, CRDO, CRWD, NVDA, QQQ, SPY]","(Editor’s note: The future prices of benchmark tracking ETFs, and the headline were updated in the story.)\n\n\n\nU.S. stock futures fell sharply on Tuesday following Monday’s mixed close. Futures of the major benchmark indices were negative amid the ongoing Iran-U.S. conflict."
22,50993844,Benzinga Newsdesk,2026-03-03 11:35:24+00:00,"Akamai Acquires Thousands Of NVIDIA Blackwell GPUs To Power Global Distributed AI Inference Platform Across 4,400 Locations",benzinga,"[AKAM, NVDA]",
23,50992929,Anusuya Lahiri,2026-03-03 10:19:32+00:00,Nvidia Pumps $4 Billion Into Laser Tech To Fuel Next AI Supercycle,benzinga,"[AAPL, AMD, AMZN, AVGO, COHR, CSCO, LITE, META, NVDA, SFTBY, TMUS, TSLA, TSM]",Nvidia invests $4B in photonics partners and expands into 6G with telecom companies for AI-driven networks.
24,50992799,Vandana Singh,2026-03-03 10:10:00+00:00,Coherent Stock Pulls Back After 15% Surge On Multibillion Nvidia AI Deal,benzinga,"[COHR, NVDA]",Coherent (COHR) stock dips premarket after a 15% surge on a $2B Nvidia deal to advance AI data center optics. Get the full market analysis.
25,50992305,Rishabh Mishra,2026-03-03 09:15:30+00:00,"SanDisk Surges Over 160% In 2026, Outpacing Software's 23% Slump As 'Big Money' Shifts To AI Infra",benzinga,"[IGV, LRCX, MU, NVDA, SNDK]",Lucas Downey details why &#34;big money&#34; is shifting from software to AI hardware as SanDisk hits 161% YTD gains and the IGV drops 23%.
26,50985508,Benzinga Newsdesk,2026-03-02 21:52:46+00:00,"'US Mulls Capping Nvidia H200 Sales at 75,000 per Chinese Customer'- Bloomberg",benzinga,"[FXI, NVDA]",
27,50977275,Daragh Thomas,2026-03-02 18:14:06+00:00,'Big Short' Legend Steve Eisman Calls Nvidia's 73% Revenue Growth 'Incredible',benzinga,"[NVDA, OWL]","Steve Eisman, investor, called it incredible&#39; that Nvidia grew revenue 73% in a year, but stock closed down. Eisman says AI spending is Nvidia&#39;s tailwind and risk. Private credit funded software buyouts at high valuation."
28,50975768,The Arora Report,2026-03-02 17:36:29+00:00,The Market's Iran Blind Spot And Positioning Risk,benzinga,"[AAOI, AAPL, AMZN, AVAV, BA, BTCUSD, COHR, CVX, DPRO, EOG, EQT, EXE, GLD, GLW, GOOG, HAL, ITA, KTOS, LASR, LITE, META, MSFT, NEM, NVDA, OIH, QQQ, RCAT, RRC, RTX, SHEL, SLV, SPY, TSLA, USO]",\n\n\n\nPositioning\n\n\n
29,50975716,Benzinga Insights,2026-03-02 17:35:19+00:00,10 Information Technology Stocks Whale Activity In Today's Session,benzinga,"[AAOI, ALAB, CRM, LITE, MSFT, MU, NVDA, PLTR, RIOT, TSM]",
30,50974461,Lekha Gupta,2026-03-02 17:06:10+00:00,Nvidia Backs Lumentum With Billions To Scale AI Infrastructure,benzinga,"[LITE, NVDA]","Nvidia and Lumentum have entered a strategic partnership to develop optics technology, with a substantial investment from Nvidia."
31,50974333,Benzinga Newsdesk,2026-03-02 17:03:49+00:00,'Nvidia-Backed 'Open' AI Start-Up Courts Investors At $20B-plus Valuation' - Financial Times,benzinga,[NVDA],
32,50973174,Akanksha Bakshi,2026-03-02 16:42:58+00:00,Flex Teams Up With AMD To Supercharge US AI Infrastructure Buildout,benzinga,"[AMD, FLEX, INTC, NVDA, SMH, SOXX]",Flex Ltd. (FLEX) stock rose on news of collaboration with Advanced Micro Devices Inc. (AMD) to boost domestic AI capacity.
33,50966106,Anusuya Lahiri,2026-03-02 14:37:07+00:00,"Alibaba Unifies AI Brand, Goes All-In On 'Qwen'",benzinga,"[AAPL, AMD, AMZN, AVGO, BABA, META, NVDA, TSLA, TSM]","Alibaba (BABA) is ditching multiple confusing names to unite its entire AI empire under one brand: Qwen. From foundation models to a new flagship app, see how the &#34;Amazon of China&#34; is simplifying its tech to win the global AI race."
34,50963112,Benzinga Newsdesk,2026-03-02 13:11:48+00:00,NVIDIA And Coherent Announce Multi-Year Strategic Partnership To Develop Optic Tech For AI Infrastructure,benzinga,"[COHR, NVDA]",
35,50962782,Benzinga Newsdesk,2026-03-02 13:06:18+00:00,Nvidia Investing $12B In Lumentum To Advance Optics Technologies,benzinga,"[LITE, NVDA]",
36,50961332,Rishabh Mishra,2026-03-02 12:28:21+00:00,Stan Druckenmiller Says He 'Screwed It Up' With His Nvidia Holdings After Seeing 'Disturbingly Heated' Signals In Tech,benzinga,[NVDA],Stan Druckenmiller admits he ‘screwed it up&#39; on Nvidia after seeing ‘disturbingly heated&#39; AI signals. His hard lessons on the tech bubble.
37,50959411,Avi Kapoor,2026-03-02 11:31:18+00:00,5 Stocks In The Spotlight From Wall Street's Most Accurate Analysts Last Month,benzinga,"[ALSN, ARRY, DCO, GLW, NVDA]",Top analysts reveal their latest stock picks and price targets. Benzinga&#39;s Analyst Ratings API offers exclusive and accurate insights for investors to outperform the market.
38,50959360,Anusuya Lahiri,2026-03-02 11:29:14+00:00,"Nvidia, World Telecom Leaders Launch AI-Driven Blueprint For 6G",benzinga,"[AAPL, AMD, AMZN, AVGO, CSCO, DTEGF, META, NVDA, SFTBY, SKM, TMUS, TSLA, TSM]",Nvidia unveils 6G initiative with global partners at MWC. AI-driven network designs aim to improve security/trust.
39,50957976,Anusuya Lahiri,2026-03-02 09:49:36+00:00,Supermicro Eyes Telecom Boom With Scalable AI RAN Infrastructure,benzinga,"[AMD, AVGO, NOK, NVDA, SKM, SMCI, TELNY]",Supermicro expands into AI-RAN to optimize telecom networks and support operators in deploying AI solutions effectively.
40,50957746,Namrata Sen,2026-03-02 09:29:31+00:00,"Tom Lee Expects March To Be 'Turnaround Month,' Calls Growth Scare More Of 'Risk Premium' Than Actual Concern",benzinga,"[NVDA, SPY, VOO]",Tom Lee of Fundstrat Global Advisors acknowledged uncertainty around the AI trade but remains optimistic that things could turn for the better in March.
41,50957181,Avi Kapoor,2026-03-02 08:08:35+00:00,Dow Dips Over 500 Points Following Wholesale Inflation Data: Greed Index Remains In 'Fear' Zone,benzinga,"[AAOI, ADT, DELL, NCLH, NFLX, NVDA, SEE, WBD]","The CNN Money Fear and Greed Index shows minimal change in market sentiment with a reading of 42.9, remaining in the Fear zone on Friday."
42,50956746,Benzinga Newsdesk,2026-03-02 07:21:02+00:00,"Reported Sunday, NVIDIA And Eleven Global Telecom Leaders Commit At MWC To Build AI-Native, Open And Secure 6G Wireless Networks On Software-Defined Platforms",benzinga,[NVDA],
43,50956025,Ananya Gairola,2026-03-02 04:43:03+00:00,Cathie Wood Sees Competition For Nvidia As ARK Projects Custom Silicon Boom By 2030: Amazon Is The 'Sleeping Giant',benzinga,"[AMD, AMZN, GOOG, GOOGL, META, NVDA]","Cathie Wood warned that rising competition from custom AI chips—led by players like Amazon.com Inc. and Alphabet Inc.—could challenge Nvidia&#39;s dominance, as ARK projects custom silicon may capture over one-third of the compute market by 2030."

# FinBERT

In [24]:
class FinbertSentiment:
    def __init__(self):
        device = "gpu" if torch.cuda.is_available() else "cpu"
        self.pipe = pipeline(
            "sentiment-analysis", model="ProsusAI/finbert", device = device)

    def calc_sentiment_score(self, df, col):
        news_data = df[col].to_list()        
        sentiment = self.pipe(news_data, batch_size=32) 

        temp_df = pd.json_normalize(sentiment).rename(columns={
        'label': f'{col}_predicted_label',
        'score': f'{col}_probability_score'
    })
        df = pd.concat([df, temp_df], axis=1)
        
        return df

In [25]:
model = FinbertSentiment()

Loading weights: 100%|███████████████████████| 201/201 [00:00<00:00, 299.15it/s, Materializing param=classifier.weight]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [26]:
df = model.calc_sentiment_score(news_df, "headline")
df = model.calc_sentiment_score(df, "summary")
df.head(2)

,id,author,publish_time,headline,source,related_tickers,summary,headline_predicted_label,headline_probability_score,summary_predicted_label,summary_probability_score
0,50957976,Anusuya Lahiri,2026-03-02 09:49:36+00:00,Supermicro Eyes Telecom Boom With Scalable AI RAN Infrastructure,benzinga,"[AMD, AVGO, NOK, NVDA, SKM, SMCI, TELNY]",Supermicro expands into AI-RAN to optimize telecom networks and support operators in deploying AI solutions effectively.,neutral,0.624750,positive,0.741093
1,50957746,Namrata Sen,2026-03-02 09:29:31+00:00,"Tom Lee Expects March To Be 'Turnaround Month,' Calls Growth Scare More Of 'Risk Premium' Than Actual Concern",benzinga,"[NVDA, SPY, VOO]",Tom Lee of Fundstrat Global Advisors acknowledged uncertainty around the AI trade but remains optimistic that things could turn for the better in March.,neutral,0.584198,positive,0.901160

In [27]:
headlines = df[["headline", "headline_predicted_label", "headline_probability_score"]]

In [28]:
pd.set_option('display.max_colwidth', None)
display(headlines)

,headline,headline_predicted_label,headline_probability_score
0,Supermicro Eyes Telecom Boom With Scalable AI RAN Infrastructure,neutral,0.624750
1,"Tom Lee Expects March To Be 'Turnaround Month,' Calls Growth Scare More Of 'Risk Premium' Than Actual Concern",neutral,0.584198
2,Dow Dips Over 500 Points Following Wholesale Inflation Data: Greed Index Remains In 'Fear' Zone,negative,0.962430
3,"Reported Sunday, NVIDIA And Eleven Global Telecom Leaders Commit At MWC To Build AI-Native, Open And Secure 6G Wireless Networks On Software-Defined Platforms",positive,0.526888
4,Cathie Wood Sees Competition For Nvidia As ARK Projects Custom Silicon Boom By 2030: Amazon Is The 'Sleeping Giant',neutral,0.783395

In [29]:
summary = df[["summary", "summary_predicted_label", "summary_probability_score"]]
pd.set_option('display.max_colwidth', None)
display(summary)

,summary,summary_predicted_label,summary_probability_score
0,Supermicro expands into AI-RAN to optimize telecom networks and support operators in deploying AI solutions effectively.,positive,0.741093
1,Tom Lee of Fundstrat Global Advisors acknowledged uncertainty around the AI trade but remains optimistic that things could turn for the better in March.,positive,0.901160
2,"The CNN Money Fear and Greed Index shows minimal change in market sentiment with a reading of 42.9, remaining in the Fear zone on Friday.",negative,0.777337
3,,neutral,0.424185
4,"Cathie Wood warned that rising competition from custom AI chips—led by players like Amazon.com Inc. and Alphabet Inc.—could challenge Nvidia&#39;s dominance, as ARK projects custom silicon may capture over one-third of the compute market by 2030.",negative,0.568356

## finBERT FinancialPhraseBank

run inference on the FinancalPhraseBank data (this is what the model was originally fine tuned on)

In [143]:
fpb_data = [] # FinancialPhraseBank

with open("FinancialPhraseBank-v1.0/Sentences_50Agree.txt", "r") as f:
    for line in f:
        sentence = line.strip().split('@')
        headline, label = sentence[0], sentence[1]
        fpb_data.append({
            "headline": headline,
            "true_label": label
        })

In [144]:
fpb_df = pd.DataFrame(fpb_data)

In [31]:
fpb_sentiment = model.calc_sentiment_score(fpb_df, "headline")

NameError: name 'fpb_df' is not defined

In [160]:
correct_pred = fpb_sentiment[fpb_sentiment["true_label"].values == fpb_sentiment["headline_predicted_label"].values]
accuracy =  len(correct_pred)/ len(fpb_sentiment)
print("---Financial Phrase Bank---\n")
print(f"finBERT accuracy: {accuracy*100:.2f}%")

---Financial Phrase Bank---

finBERT accuracy: 88.96%

## finBERT FiQA

In [162]:
from datasets import load_dataset

In [165]:
fiqa_dataset = load_dataset("TheFinAI/fiqa-sentiment-classification")

fiqa_dataset["train"].to_csv("fiqa_train.csv")
fiqa_dataset["valid"].to_csv("fiqa_valid.csv")
fiqa_dataset["test"].to_csv("fiqa_test.csv")

C:\Users\kiera\miniconda3\envs\diss-notebook\lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\kiera\.cache\huggingface\hub\datasets--TheFinAI--fiqa-sentiment-classification. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████████████████████████████████████████| 822/822 [00:00<00:00, 26206.63 examples/s]
Generating test split: 100%|████████████████████████████████████████████████| 234/234 [00:00<00:00, 7543.77 examples/s]
Generating valid split: 100%|███████████████████████████████████████████████| 117/117 [00:00<00:00, 4334.57 examples/s]
Creating CSV from Arrow format: 100%|████████████████████████████████████████████████████| 1/1 [00:00<00:00, 38.26ba/s]
Creating CSV from Arrow format: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 210.93ba/s]
Creating CSV from Arrow format: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00, 205.17ba/s]

30193

In [168]:
fiqa_df = pd.read_csv('fiqa_train.csv')
fiqa_df.head()

,_id,sentence,target,aspect,score,type
0,1,Royal Mail chairman Donald Brydon set to step down,Royal Mail,Corporate/Appointment,-0.374,headline
1,100,Slump in Weir leads FTSE down from record high,Weir,Market/Volatility/Volatility,-0.827,headline
2,1000,AstraZeneca wins FDA approval for key new lung cancer pill,AstraZeneca,Corporate/Regulatory,0.549,headline
3,1002,UPDATE 1-Lloyds to cut 945 jobs as part of 3-year restructuring plan,Lloyds,Corporate/Strategy,-0.266,headline
4,1005,Standard Chartered Shifts Emerging-Markets Strategy After Losses,Standard Chartered,Corporate/Strategy,-0.461,headline

In [180]:
def rough_score_to_label(score):
    if score < -0.1:
        return "negative"
    elif score > 0.1:
        return "positive"
    else:
        return "neutral"

fiqa_df["rough_true_label"] = fiqa_df["score"].apply(rough_score_to_label)

In [189]:
fiqa_sentiment = model.calc_sentiment_score(fiqa_df, "sentence")

In [190]:
fiqa_sentiment.head()

,_id,sentence,target,aspect,score,type,rough_true_label,sentence_predicted_label,sentence_probability_score
0,1,Royal Mail chairman Donald Brydon set to step down,Royal Mail,Corporate/Appointment,-0.374,headline,negative,neutral,0.704659
1,100,Slump in Weir leads FTSE down from record high,Weir,Market/Volatility/Volatility,-0.827,headline,negative,negative,0.968347
2,1000,AstraZeneca wins FDA approval for key new lung cancer pill,AstraZeneca,Corporate/Regulatory,0.549,headline,positive,positive,0.817536
3,1002,UPDATE 1-Lloyds to cut 945 jobs as part of 3-year restructuring plan,Lloyds,Corporate/Strategy,-0.266,headline,negative,negative,0.968914
4,1005,Standard Chartered Shifts Emerging-Markets Strategy After Losses,Standard Chartered,Corporate/Strategy,-0.461,headline,negative,neutral,0.907707

In [192]:
correct_pred = fiqa_sentiment[fiqa_sentiment["rough_true_label"].values == fiqa_sentiment["sentence_predicted_label"].values]
accuracy =  len(correct_pred)/ len(fiqa_sentiment)
print("---FiQa dataset---\n")
print(f"finBERT accuracy: {accuracy*100:.2f}%")

---FiQa dataset---

finBERT accuracy: 48.78%

In [194]:
print("The above accuracy is quite low, but the \'true label\' column has not been calculated properly. To calculate it properly, \
I need to change finBERT from a classification to a regression model. You do this by adjusting the final output layer from 3 neurons \
(positive, negative, neutral) to a one-layer neuron that evaluates based on MSE instead of accuracy.")

The above accuracy is quite low, but the 'true label' column has not been calculated properly. To calculate it properly, I need to change finBERT from a classification to a regression model. You do this by adjusting the final output layer from 3 neurons (positive, negative, neutral) to a one-layer neuron that evaluates based on MSE instead of accuracy.

In [195]:
print("Next steps: test on more datasets and change the output layer of the model so it's more appropriate for the FiQa dataset")

Next steps: test on more datasets and change the output layer of the model so it's more appropriate for the FiQa dataset

# finGPT