# AAPL headline relevance, tone, and forward-return check

This notebook classifies each AAPL headline once with a five-shot prompt as **relevant** or **not relevant** to the ticker's stock-price drivers, then examines the tone of the relevant headlines against later AAPL returns.

The model sees only the target ticker, publication date, and article title. It does **not** receive Alpha Vantage ticker relevance, sentiment, topics, article summaries, price data, returns, or events. The `tickers` and `topics` dataset partitions are never downloaded.

This is not model training or fine-tuning: `n-shot` means adding `n` completed examples to the prompt at inference time. Run this on a CUDA machine; it intentionally refuses CPU inference.

In [28]:
from __future__ import annotations

import os
import re
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from huggingface_hub import hf_hub_download

pd.set_option("display.max_colwidth", 160)
pd.set_option('display.max_rows', 1000)

DATASET_REPO = "cookekieran/alphavantage-market-news"
MONTHS = pd.period_range("2023-01", "2026-06", freq="M").astype(str).tolist()
TICKER = "AAPL"
SAMPLE_SIZE = None  # None means every AAPL article in the configured months.
SHOT_COUNTS = [5]  # The requested five-shot filter; every headline is parsed once.
MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
for candidate in (PROJECT_ROOT / ".env", PROJECT_ROOT / "env.txt"):
    if candidate.exists():
        load_dotenv(candidate)

HF_TOKEN = os.getenv("HF_TOKEN")
print({"dataset": DATASET_REPO, "month": MONTHS, "ticker": TICKER, "sample_size": SAMPLE_SIZE, "model": MODEL_ID})

python-dotenv could not parse statement starting at line 3

{'dataset': 'cookekieran/alphavantage-market-news', 'month': ['2023-01', '2023-02', '2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09', '2023-10'], 'ticker': 'AAPL', 'sample_size': 500, 'model': 'Qwen/Qwen2.5-7B-Instruct'}

## 1. Load only article titles and publication dates

`requested_entity` is used only to retrieve a manageable ticker-specific sample. It is not passed to the model. This is deliberately different from the original notebook's join to Alpha Vantage ticker relevance and sentiment.

In [29]:
article_frames = []

for month in MONTHS:
    articles_path = Path(
        hf_hub_download(
            repo_id=DATASET_REPO,
            repo_type="dataset",
            filename=f"articles/{month}.parquet",
            token=HF_TOKEN,
        )
    )

    month_articles = pd.read_parquet(articles_path)
    article_frames.append(month_articles)

articles = pd.concat(article_frames, ignore_index=True)

required_columns = {"article_uid", "requested_entity", "time_published", "title"}
missing_columns = required_columns - set(articles.columns)
assert not missing_columns, f"Article data is missing: {sorted(missing_columns)}"

article_sample = (
    articles.loc[
        articles["requested_entity"].eq(TICKER),
        ["article_uid", "time_published", "title"],
    ]
    .dropna(subset=["time_published", "title"])
    .drop_duplicates("article_uid")
    .sort_values(["time_published", "article_uid"])
    .reset_index(drop=True)
)
if SAMPLE_SIZE is not None:
    article_sample = article_sample.head(SAMPLE_SIZE).reset_index(drop=True)

article_sample["time_published"] = pd.to_datetime(
    article_sample["time_published"], utc=True
)

display(article_sample[["time_published", "title"]])

,time_published,title
0,2023-01-02 04:52:00+00:00,What is TSMC?
1,2023-01-03 04:06:10+00:00,"If You Invested $100 in Berkshire Hathaway in 1965, This Is How Much You Would Have Today"
2,2023-01-03 04:06:10+00:00,"If You Invested $100 in Berkshire Hathaway in 1965, This Is How Much You Would Have Today"
3,2023-01-03 12:05:00+00:00,Tuesday's ETF with Unusual Volume: IWL
4,2023-01-04 09:26:00+00:00,Salesforce to lay off 10% of workforce to cut costs amid economic downturn
5,2023-01-04 11:52:00+00:00,Apple to sign Luxshare for iPhone production in China - FT
6,2023-01-05 03:59:02+00:00,Apple brings AI narration to audiobooks
7,2023-01-05 15:29:00+00:00,"Android has a response to iPhone’s satellite connection, thanks to Qualcomm"
8,2023-01-06 04:25:43+00:00,Nordstrom appoints Atticus Tysen to its board of directors
9,2023-01-06 04:25:59+00:00,Qualcomm partners with Iridium to develop satellite connectivity
10,2023-01-06 04:31:08+00:00,Apple Analyst Says BOE Will Become Largest Display Supplier for iPhone 15
11,2023-01-06 04:51:24+00:00,Kartoon Channel! Expands Global Reach
12,2023-01-06 11:11:00+00:00,Garmin Venu Sq2 Review | A fitness lifestyle companion
13,2023-01-08 04:57:03+00:00,You might actually want a TiVo TV someday
14,2023-01-09 16:15:00+00:00,U.S. Supreme Court lets Meta's WhatsApp pursue 'Pegasus' spyware suit
15,2023-01-10 04:03:16+00:00,Inari’s share price down over 4% as Apple plans to drop Broadcom chip from devices
16,2023-01-10 04:24:59+00:00,"Illumina, the DNA sequencing giant, gives Wall Street bad news"
17,2023-01-10 13:45:00+00:00,"Pepsi, Coke soda pricing targeted in new federal probe"
18,2023-01-11 01:39:00+00:00,Apple to start using in-house screens from 2024 - Bloomberg News
19,2023-01-11 04:03:16+00:00,Inari pares loss as analysts see limited impact from Apple's plan to drop Broadcom chip
20,2023-01-11 04:31:49+00:00,Apple Watch patent infringement finding; Masimo seeks import ban
21,2023-01-11 04:57:25+00:00,Apple debuts free tool to help businesses get noticed
22,2023-01-11 12:38:00+00:00,Kuo doubles down on iPhone 15 Pro having no physical buttons
23,2023-01-12 02:31:00+00:00,Back Again At Comparing Skyworks Vs. Qorvo (NASDAQ:SWKS)
24,2023-01-12 04:26:17+00:00,"IDC, Gartner: 2022 PC Demand Dropped To Its ‘Lowest Level In Years’"
25,2023-01-12 04:45:34+00:00,Starbucks tells corporate employees to return to the office
26,2023-01-12 22:43:00+00:00,Starbucks tells corporate employees to return to office 3 days a week
27,2023-01-13 03:59:02+00:00,Apple CEO Tim Cook to take a more than 40 percent pay cut
28,2023-01-13 03:59:02+00:00,Apple CEO Tim Cook to take more than 40% pay cut
29,2023-01-13 11:45:00+00:00,Apple Takes Major Steps Toward ‘Owning’ Its Key Technology
30,2023-01-16 04:53:01+00:00,"From Apple To Amazon And Toyota, Here Are The Top 10 Biggest Companies In The World"
31,2023-01-18 04:26:55+00:00,Goldman Sachs Vs. Jefferies: Which Is the Better Investment?
32,2023-01-18 04:52:00+00:00,TSMC expects revenue to fall amid declining chip demand
33,2023-01-18 05:21:00+00:00,Temu Review: What Is Temu and Why Is It Suddenly America’s Most Popular App?
34,2023-01-19 04:35:32+00:00,"Netflix’s Reed Hastings steps aside as co-CEO, stays on as executive chairman"
35,2023-01-19 13:12:00+00:00,Apple’s Reliance On China Poses A Problem For The Company
36,2023-01-21 04:57:44+00:00,予算3万円台の「スマートウォッチ」おすすめ5選 人気の「Apple Watch SE」から、コスパが良い高機能モデルまで【2023年1月版】 - Fav-Log by ITmedia
37,2023-01-23 05:49:00+00:00,7 Growth Stocks That Will Make You Rich in 10 Years
38,2023-01-23 06:27:00+00:00,How Apple’s Upcoming Mixed-Reality Headset Will Work
39,2023-01-23 17:12:00+00:00,"Nokia Corp. ADR rises Monday, still underperforms market"
40,2023-01-24 03:59:02+00:00,Apple builds on privacy commitment by unveiling new education and awareness efforts on Data Privacy Day
41,2023-01-24 17:12:00+00:00,Nokia Corp. ADR underperforms Tuesday when compared to competitors
42,2023-01-25 04:08:33+00:00,Choice Hotels Opens Cambria Hotel Austin Uptown Near the Domain
43,2023-01-25 04:21:29+00:00,Goldman Sachs signals partial retreat from consumer banking
44,2023-01-25 07:00:00+00:00,"Big Tech to Congress: Listen to Taylor Swift and Go After Ticketmaster, Not Us"
45,2023-01-26 00:00:00+00:00,"AST SpaceMobile raises $75 million, partners with TIM Brasil"
46,2023-01-30 04:21:00+00:00,Google continued to ramp up federal lobbying spending before DOJ filed second antitrust lawsuit
47,2023-01-30 04:30:31+00:00,‘Acapulco’ Renewed for Season 3 at Apple
48,2023-01-31 04:04:01+00:00,Get Your Game on With Build-a-Bear's New 'Ted Lasso' Collection
49,2023-01-31 06:27:00+00:00,"Apple workplace rules violate U.S. labor law, agency finds"
50,2023-01-31 16:31:00+00:00,"Netflix Inc. stock rises Tuesday, still underperforms market"
51,2023-02-01 10:41:00+00:00,Spotify Reports Q4 2022 Earnings: Strong User Growth and Widened Losses
52,2023-02-02 03:03:59+00:00,Apple Is Dropping Industrial Design Chief Role in Post-Jony Ive Era
53,2023-02-02 03:32:30+00:00,McDonald’s new strategy to bring renewable energy to its supply chain
54,2023-02-02 03:42:29+00:00,"Samsung’s next frontier: XR in partnership with Qualcomm, Google"
55,2023-02-02 12:10:00+00:00,Apple sales drop 5% in largest quarterly revenue decline since 2016
56,2023-02-03 03:03:59+00:00,"Apple Q1 2023 Revenues Slowed by Exchange Rates, COVID, and Inflation"
57,2023-02-03 03:32:49+00:00,Meta从虚拟元宇宙重回现实
58,2023-02-03 14:30:00+00:00,Peloton Rival Zwift Bets on Hardcore Racing In Your Living Room
59,2023-02-06 02:45:00+00:00,"Corning Inc. recently cut about 1,500 jobs worldwide"
60,2023-02-06 03:03:59+00:00,NLRB: Apple illegally interfered with employees’ protected activity
61,2023-02-06 03:07:53+00:00,Purifying the ‘miracle metal’: How to decarbonize aluminium
62,2023-02-06 03:48:27+00:00,Sonos Is Having a Secret Sale Ahead of President's Day
63,2023-02-07 03:32:49+00:00,元宇宙烧了 137 亿美元，还得 Facebook 救 Meta
64,2023-02-07 15:30:16+00:00,BioSig Appoints Steve Buhaly as CFO
65,2023-02-08 03:50:48+00:00,Exclusive: Hearing startup Tuned adds more employers with fresh funds
66,2023-02-09 10:19:00+00:00,"AMD wins nearly a third of processor market, Arm's climb slows: analyst report"
67,2023-02-10 08:30:00+00:00,Cartões Bradesco seguem pontuando em compras com Apple Pay
68,2023-02-11 03:32:43+00:00,Apple hires its first Chief People Officer in executive reshuffle
69,2023-02-14 05:25:00+00:00,T-Mobile suffers major network outage across US
70,2023-02-15 16:53:00+00:00,Qualcomm introduces new Snapdragon X75 mobile modem chip
71,2023-02-16 08:00:00+00:00,Forget Milk and Eggs: Supermarkets Are Having a Fire Sale on Data About You
72,2023-02-16 20:11:00+00:00,Exclusive: SoftBank's Arm China profit drops over 90% in 2022
73,2023-02-17 03:10:23+00:00,"UBS recommends its clients grab a full serving of Buffett's incredible, UNDERVALUED Berkshire Hathaway"
74,2023-02-17 15:59:00+00:00,Groupon Outsources Legal Executive Role to Winston & Strawn (1)
75,2023-02-17 16:57:00+00:00,Garmin Ltd. stock outperforms competitors despite losses on the day
76,2023-02-17 20:30:12+00:00,Familiar Faces Powering Growth Stock Resurgence
77,2023-02-20 03:00:00+00:00,Trump’s Truth Social Dilemma
78,2023-02-21 03:45:10+00:00,Major League Soccer and RBC Wealth Management Announce Multi-Year Partnership
79,2023-02-21 03:48:27+00:00,Apple HomePod 2 vs Sonos One: is it worth paying more?
80,2023-02-22 08:53:00+00:00,Dexcom G6 Continuous Glucose Monitoring System Launches in Singapore
81,2023-02-23 03:08:59+00:00,2023 Clean200
82,2023-02-23 03:10:23+00:00,All 47 Warren Buffett Portfolio Stocks Now | Current 2023 Holdings List
83,2023-02-23 03:58:43+00:00,Mercedes-Benz’s Superscreen Will Bring TikTok and Zoom to E-Class EVs
84,2023-02-23 10:14:00+00:00,7 Super Speculative Stocks That Could Make You Very Rich
85,2023-02-23 14:38:00+00:00,Unity Software stock slides nearly 20% as mobile-ad spending dries up and annual forecast weighs
86,2023-02-23 18:04:00+00:00,Apple shareholder moves to boot Al Gore from board of directors
87,2023-02-25 03:21:39+00:00,Step-By-Step Guide To Opening A moomoo Account
88,2023-02-26 07:40:00+00:00,How Reuters used AirTags to reveal Dow’s false recycling promises
89,2023-02-27 03:10:23+00:00,"If I'd invested $1,000 in Berkshire Hathaway shares 25 years ago, here's how much I'd have now!"
90,2023-02-27 03:49:42+00:00,How Have the Top U.S. Asset Managers Voted in 2022?
91,2023-02-27 10:32:00+00:00,Apple pays $12.1 mln fine for alleged app market abuse in Russia - Antimonopoly Service
92,2023-02-27 12:11:00+00:00,"Apple iPhone's Clean Energy Charging causes stir on social media over battery charging times, 'shaming'"
93,2023-02-28 14:40:41+00:00,Lightsource bp Places Multi-Year Order for 4GW of First Solar Modules
94,2023-02-28 20:09:15+00:00,PY Top Holdings List & Exposure (Principal Value ETF)
95,2023-03-01 00:00:00+00:00,Why Target says 2022 was rougher than 2020
96,2023-03-02 02:59:16+00:00,The 10 most innovative companies in augmented and virtual reality of 2023
97,2023-03-02 16:00:00+00:00,PNC Bank ends business relationship with Donald Trump Jr's MxM News app company 'without cause'
98,2023-03-03 09:01:00+00:00,British chip giant Arm chooses New York listing in a blow to London
99,2023-03-05 14:00:00+00:00,"Apple Readies Its Next Range of Macs, Including — Finally — a New iMac"
100,2023-03-07 06:00:00+00:00,"Sonos CEO Patrick Spence on right to repair, spatial audio and those never-ending lawsuits"
101,2023-03-07 14:31:14+00:00,Virtual try-on is being hit by class actions. Should brands worry?
102,2023-03-09 02:13:32+00:00,Apple and Foxconn efforts win labour reforms to advance Indian production plans - FT
103,2023-03-09 02:55:24+00:00,Sonos Bets on Spatial Audio as a Key Brand Differentiator
104,2023-03-10 00:00:00+00:00,Apple Inc. to Launch Apple Music Classical App
105,2023-03-12 02:23:44+00:00,Four Ways to Cluster based on Correlation
106,2023-03-12 10:59:00+00:00,"From Apple to Boeing, India is being put to the test as China manufacturing alternative"
107,2023-03-14 02:13:31+00:00,Federal Circuit Allows Apple’s Fintiv Challenge To Proceed
108,2023-03-14 08:36:00+00:00,Fall Detection Systems Market Current Status and Future
109,2023-03-16 03:03:45+00:00,MLBN and Apple TV+ national broadcasts to show Zoom Replay Operations Center live under new deal
110,2023-03-19 18:23:00+00:00,Buffett's Berkshire Hathaway speeds up stock buybacks
111,2023-03-21 05:31:16+00:00,"For Broad-Based Large-Cap ESG Exposure, See CVLC"
112,2023-03-21 19:52:34+00:00,"Consider CVLC for Broad-Based, Large-Cap ESG Exposure"
113,2023-03-24 02:43:46+00:00,Friday Q&A: Movano takes on the women’s wearables market with a smart ring
114,2023-03-24 02:58:55+00:00,Taiwan PCB makers moving production to Southeast Asia
115,2023-03-25 02:19:10+00:00,Beloved clothing store closes - leaving customers scrambling for new options
116,2023-03-25 07:17:41+00:00,Skip Big Tech And Buy Bank of America (NYSE:BAC)
117,2023-03-27 02:13:31+00:00,Apple CEO Tim Cook meets with China's commerce minister on supply chain
118,2023-03-28 00:00:00+00:00,Apple introduces Apple Pay Later to allow consumers to pay for purchases over time
119,2023-03-28 02:14:03+00:00,AutoCAD for Mac 2024: New Collaboration Enhancements and Improved Performance With M-Series Chips
120,2023-03-28 22:49:00+00:00,"Apple launches 'buy now, pay later' service in US"
121,2023-03-29 02:13:31+00:00,"Apple Introduces Buy Now, Pay Later Service. Here's How It Will Work."
122,2023-03-29 12:08:00+00:00,Live Nation head says ‘speculative ticketing’ to blame for difficulty with buying event tickets
123,2023-03-31 02:13:31+00:00,Apple lawsuit claims company fails to pay overtime compensation at correct rate
124,2023-03-31 06:40:09+00:00,Do ESG Funds Have Higher ESG Scores?
125,2023-03-31 18:45:00+00:00,Apple wins appeal against UK's decision to investigate its mobile browser
126,2023-04-03 01:41:21+00:00,Garmin Forerunner 265 review: Brilliant but far too expensive
127,2023-04-04 00:08:50+00:00,XBIL Stock Price | US Treasury 6 Month Bill ETF
128,2023-04-05 01:20:42+00:00,Apple and global suppliers expand renewable energy to 13.7 gigawatts
129,2023-04-05 14:40:48+00:00,Frontdoor App Changes the Game of Home Repair and Maintenance
130,2023-04-06 01:40:33+00:00,General Motors hates your iPhone
131,2023-04-06 06:08:00+00:00,Apple says 'Hello Mumbai' at first India store launch
132,2023-04-08 17:50:00+00:00,Apple sued to stop App Store clones of Baidu's Ernie AI chatbot
133,2023-04-09 01:46:15+00:00,Social Livestreaming Platform Bigo Live Removed From App Store
134,2023-04-10 07:07:00+00:00,Introducing Domino's® on Apple CarPlay®: The Easiest Way to Order Pizza on the Go
135,2023-04-10 14:30:06+00:00,Domino’s Introduces In-Car Ordering
136,2023-04-10 18:10:00+00:00,"Baidu sues Apple, app developers over fake Ernie bot apps"
137,2023-04-12 01:31:39+00:00,"Apple iPhone 15 Pro, iPhone 15 Pro Max Might Stick To Physical Instead Of Solid State Buttons"
138,2023-04-12 02:07:30+00:00,"TSMC’s Taiwan factory plans have not changed, says minister"
139,2023-04-13 00:00:00+00:00,Apple will use 100 percent recycled cobalt in batteries by 2025
140,2023-04-13 01:30:18+00:00,Legal Briefs: News From Around NH
141,2023-04-13 01:57:20+00:00,"10 up-and-coming stocks, according to Gen Z"
142,2023-04-13 04:06:00+00:00,Apple Triples India iPhone Output to $7 Billion in China Shift
143,2023-04-16 01:20:42+00:00,Apple Plans to Launch More Than Just Its New Headset at WWDC
144,2023-04-16 13:39:48+00:00,"Tradr 2X Short TSLA Daily ETF (TSLQ) News, Articles, Events & Latest Updates"
145,2023-04-17 09:30:00+00:00,Autodesk Technology Engagement Center breaks ground at CSUN
146,2023-04-17 11:39:00+00:00,Ben & Jerry's ice cream 'scoopers' launch union drive
147,2023-04-17 11:59:00+00:00,Magna to engineer and build off-road electric vehicle for industrial group Ineos
148,2023-04-18 05:09:27+00:00,YieldMax APLY ETF Seeks Income Through Call Options on Apple Stock
149,2023-04-20 01:25:25+00:00,"Big Tech Illegally Uses NDAs to Silence Would-Be-Whistleblowers, SEC Tips Allege"
150,2023-04-21 17:09:01+00:00,Evaluating ESG’s Role in Creating Value
151,2023-04-24 14:39:40+00:00,Eye on Tap to Pay: MagicCube Teams Up With ACI; Fiserv Offers Tap to Pay on Clover
152,2023-04-27 01:49:47+00:00,"In Masimo v. Apple Trial Twist, Jurors Suddenly Learn Apple Hired Many Masimo Employees"
153,2023-04-27 16:20:00+00:00,Webull expands to Japan
154,2023-04-30 02:02:02+00:00,"Starbucks, Ford, Apple Lead Another Busy Earnings Week"
155,2023-05-01 18:02:00+00:00,"Forerunner 965, 265, 265S: Everything to know about Garmin’s first AMOLED display-toting running watches in India"
156,2023-05-02 00:00:00+00:00,"If Expense Ratio Really Mattered, Most of These ETFs Would Dominate"
157,2023-05-02 00:58:13+00:00,Masimo v. Apple – Judge Declares a Mistrial as Jury Hopelessly Deadlocked
158,2023-05-02 15:34:00+00:00,Apple fights $2 billion London lawsuit for 'throttling' millions of iPhones
159,2023-05-03 22:16:00+00:00,Qualcomm outlook grim as smartphone sales stay weak
160,2023-05-04 00:58:13+00:00,"Joe Kiani, Co-founder and CEO of Masimo, Talks About Fighting Corporate Giants and His Fixation on Reducing Preventable Hospital Deaths"
161,2023-05-04 05:30:00+00:00,CEO Tim Cook says layoffs are a 'last resort' and not something Apple is considering right now
162,2023-05-05 13:00:00+00:00,Warren Buffett's Berkshire Hathaway has been a fortress stock during recessions and bear markets. Here's how
163,2023-05-05 14:32:00+00:00,"Apple stakes future growth on emerging markets, starting with India"
164,2023-05-06 23:02:00+00:00,Buffett says Apple is Berkshire portfolio's best business
165,2023-05-08 00:34:51+00:00,My Favorite BlackBerry of All Time Is One That Everyone Hated
166,2023-05-08 01:05:40+00:00,CEO pay continues to soar – new study
167,2023-05-09 01:20:04+00:00,This Popular Brand Has Better Profit Margins Than Apple or Nike. Is the Stock a Buy?
168,2023-05-10 00:53:47+00:00,IonQ Appoints Pat Tang as VP of Research & Development
169,2023-05-12 10:00:00+00:00,Best Buy Announces New Membership Programs to Save You Money
170,2023-05-16 00:00:00+00:00,"Apple previews Live Speech, Personal Voice, and more new accessibility features"
171,2023-05-16 00:31:02+00:00,Apple investments with European suppliers surpass €20 billion annual spend
172,2023-05-21 01:04:45+00:00,"What you need to know about Temu, the online shopping app dominating download charts"
173,2023-05-23 00:31:03+00:00,Apple announces multibillion-dollar deal with Broadcom for components made in the USA
174,2023-05-23 15:46:29+00:00,Examining the Importance of Dividend Growth
175,2023-05-23 17:31:00+00:00,Apple inks multi-billion-dollar deal with Broadcom for U.S.-made chips
176,2023-05-25 06:00:00+00:00,New HP and Sonos Devices Accentuate the Ultimate Home Office Workstation
177,2023-05-25 15:20:00+00:00,Why Is Wearable Devices (WLDS) Stock Up 250%?
178,2023-05-31 00:34:29+00:00,American Express Is Approaching Generative AI Technology with Caution
179,2023-05-31 00:37:01+00:00,Apple Dominates Berkshire’s Portfolio. The Tech Stock Is Near a Record.
180,2023-05-31 18:05:00+00:00,Garmin debuts Pro versions of Fenix 7 and Epix 7 adventure smartwatches
181,2023-06-01 08:15:00+00:00,Apple Bets On The Emerging Markets Growth Story
182,2023-06-02 06:46:00+00:00,PayPal and Venmo users shouldn't store money on the apps long term
183,2023-06-02 09:19:00+00:00,Vimeo is tuning out its streaming TV apps
184,2023-06-02 14:56:00+00:00,"In challenge to Meta, Apple expected to unveil mixed-reality headset"
185,2023-06-05 00:00:00+00:00,Introducing Apple Vision Pro: Apple’s first spatial computer
186,2023-06-05 00:14:01+00:00,Is Temu Shopping App a Communist China-Based Scam That Spies on Users?
187,2023-06-06 23:51:05+00:00,Cisco Shows Breakthrough Innovation Towards AI-First Security Cloud
188,2023-06-09 16:59:00+00:00,"Apple, Amazon must face consumer lawsuit over iPhone, iPad prices, US judge rules"
189,2023-06-12 12:43:00+00:00,Bank of America execs blew $93.6 billion. Here’s how they did it.
190,2023-06-12 13:03:00+00:00,Apple Vision Pro’s External Displays from LG Display; Internal Displays from Sony
191,2023-06-14 00:25:58+00:00,"Labor Ruling Offers Unionization Path to Uber, Lyft Drivers"
192,2023-06-14 13:30:00+00:00,Sonos Era 300 Review: Spatial Audio Is a Game Changer
193,2023-06-20 00:06:42+00:00,"Analysts highlight Masimo’s advantages over Apple, Fitbit ahead of proxy vote"
194,2023-06-20 00:21:55+00:00,"Sonos Five review: is Sonos' biggest, priciest wireless speaker its best?"
195,2023-06-21 00:22:35+00:00,Spotify has higher-priced subscription plan in the pipeline: report
196,2023-06-24 01:51:48+00:00,MUSQ Global Music Industry Index ETF Review and Aggregate Rating (MUSQ)
197,2023-06-28 00:26:42+00:00,Top 10 LGBT manufacturing leaders
198,2023-06-28 23:57:29+00:00,Road to UEFA Euro 2024™ Ramps up With European Qualifiers on FOX Sports and Fubo
199,2023-06-29 14:51:21+00:00,Lenovo ‘overall winner’ of UK FRAND trial as InterDigital confirms appeal
200,2023-06-30 00:00:00+00:00,"Apple, world's most valuable public company, is first to hit $3 trillion in market value"
201,2023-06-30 00:00:00+00:00,How Apple Became a $3 Trillion Company
202,2023-06-30 06:41:00+00:00,Proposal for new Costco store in region takes a step forward
203,2023-06-30 23:41:20+00:00,Apple Is the World’s First $3 Trillion Company
204,2023-07-03 23:40:57+00:00,"Settlement checks in the mail from Roundup, EpiPen, Zoom, others"
205,2023-07-05 09:05:00+00:00,Apple loses London appeal in 4G patent dispute with Optis
206,2023-07-06 15:11:22+00:00,Kopin Corp is the Technology Seen Behind Smart AR Glasses
207,2023-07-09 22:53:14+00:00,"Apple’s Vision Pro Will Take Far Longer Than iPad, Watch to Spur Big Revenue"
208,2023-07-10 21:12:00+00:00,Apple executives fight subpoenas in shareholders' lawsuit against Qualcomm

In [30]:
# articles_path = Path(hf_hub_download(
#     repo_id=DATASET_REPO,
#     repo_type="dataset",
#     filename=f"articles/{MONTHS}.parquet",
#     token=HF_TOKEN,
# ))
# articles = pd.read_parquet(articles_path)
# required_columns = {"article_uid", "requested_entity", "time_published", "title"}
# missing_columns = required_columns - set(articles.columns)
# assert not missing_columns, f"Article partition is missing: {sorted(missing_columns)}"

# article_sample = (
#     articles.loc[articles["requested_entity"].eq(TICKER), ["article_uid", "time_published", "title"]]
#     .dropna(subset=["time_published", "title"])
#     .drop_duplicates("article_uid")
#     .sort_values(["time_published", "article_uid"])
#     .head(SAMPLE_SIZE)
#     .reset_index(drop=True)
# )
# article_sample["time_published"] = pd.to_datetime(article_sample["time_published"], utc=True)
# assert len(article_sample), f"No articles found for {TICKER} in {MONTH}."
# with pd.option_context('display.max_rows', SAMPLE_SIZE):
#     display(article_sample[["time_published", "title"]])

## 2. Fixed relevance demonstrations

These are hand-written, task-level demonstrations rather than examples selected from the test sample. They are ordered once and nested: the 3-shot prompt contains examples 1–3, while the 5-shot prompt contains examples 1–5. This makes shot count the only intentional prompt change.

In [31]:
FEW_SHOT_EXAMPLES = [
    {
        "date": "2023-01-03",
        "title": "Apple faces EU antitrust investigation over App Store practices",
        "label": "relevant",
    },
    {
        "date": "2023-01-04",
        "title": "Technology ETF increases holdings in Apple, Microsoft and Nvidia",
        "label": "not relevant",
    },
    {
        "date": "2023-01-05",
        "title": "Apple supplier reports disruption to iPhone component production",
        "label": "relevant",
    },
    {
        "date": "2023-01-06",
        "title": "Five mega-cap technology stocks investors are watching this week",
        "label": "not relevant",
    },
    {
        "date": "2023-01-09",
        "title": "Apple cuts iPhone production forecast after weaker demand report",
        "label": "relevant",
    },
]

def format_example(example: dict) -> str:
    return (
        f"Publication date: {example['date']}\n"
        f"Headline: {example['title']}\n"
        f"Classification: {example['label']}"
    )

def build_relevance_prompt(ticker: str, published_at: pd.Timestamp, title: str, shots: int) -> str:
    assert 0 <= shots <= len(FEW_SHOT_EXAMPLES)
    examples = "\n\n".join(format_example(example) for example in FEW_SHOT_EXAMPLES[:shots])
    demonstrations = f"\n\nLABELLED EXAMPLES\n{examples}" if examples else ""
    return f"""You classify financial-news headlines for ticker {ticker}.

Classify a headline as relevant only when it describes a specific development
that could directly affect {ticker}'s revenue, demand, costs, supply chain,
products, strategy, financing, competitive position, or regulatory environment.
Classify it as not relevant when {ticker} is only in an ETF, index, stock list,
peer comparison, market roundup, investment recommendation, or generic sector
commentary without a direct company-specific mechanism.

Do not predict a return or use information outside the supplied date and headline.
Reply with exactly one label: relevant or not relevant.{demonstrations}

TARGET HEADLINE
Publication date: {published_at.date().isoformat()}
Headline: {title}
Classification:""".strip()

print(build_relevance_prompt(TICKER, article_sample.loc[0, "time_published"], article_sample.loc[0, "title"], shots=2))

You classify financial-news headlines for ticker AAPL.

Classify a headline as relevant only when it describes a specific development
that could directly affect AAPL's revenue, demand, costs, supply chain,
products, strategy, financing, competitive position, or regulatory environment.
Classify it as not relevant when AAPL is only in an ETF, index, stock list,
peer comparison, market roundup, investment recommendation, or generic sector
commentary without a direct company-specific mechanism.

Do not predict a return or use information outside the supplied date and headline.
Reply with exactly one label: relevant or not relevant.

LABELLED EXAMPLES
Publication date: 2023-01-03
Headline: Apple faces EU antitrust investigation over App Store practices
Classification: relevant

Publication date: 2023-01-04
Headline: Technology ETF increases holdings in Apple, Microsoft and Nvidia
Classification: not relevant

TARGET HEADLINE
Publication date: 2023-01-02
Headline: What is TSMC?
Classification:

## 3. Superseded duplicate experiment

The active five-shot relevance run appears below. This placeholder prevents the old duplicate run from classifying the same headlines twice.

In [32]:
# Superseded duplicate experiment. The single five-shot relevance run is below.

Loading weights: 100%|██████████| 339/339 [00:04<00:00, 76.29it/s]

## 4. Superseded duplicate display

The active five-shot results are displayed after the single relevance run below.

In [33]:
# Superseded duplicate display. The active five-shot results are displayed after the single run below.

shots,article_uid,time_published,title,0_shot,1_shot,2_shot,3_shot,4_shot,5_shot
0,01c4874dbb77a5c035d5bcea5fdd3ecc,2023-07-25 09:00:00+00:00,Introducing Norton Genie - Real-Time AI-powered Scam Detection at Your Fingertips,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
1,02bd82b62c7bf1d151a0808e2b11fbe3,2023-01-10 04:03:16+00:00,Inari’s share price down over 4% as Apple plans to drop Broadcom chip from devices,relevant,not relevant,not relevant,not relevant,not relevant,not relevant
2,03a1f810e8d95ea922887e8504ff2adb,2023-04-06 01:40:33+00:00,General Motors hates your iPhone,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
3,0447c69db0ac6b359d47220f1c08bc4f,2023-09-12 20:24:00+00:00,"Apple unveils iPhone 15 Pro with titanium case, holds line on prices",relevant,relevant,relevant,relevant,relevant,relevant
4,05bda0abee450c9248ea6a0d7f7dbd0d,2023-07-14 16:32:00+00:00,Apple Inc. stock underperforms Friday when compared to competitors despite daily gains,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
5,08838071f9f5ad5de8e609dfdd8c006d,2023-09-21 14:35:48+00:00,Expedia Group builds generative AI into multiple products in its “Fall Release”,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
6,09c0d12926b75d72091155728511af52,2023-05-05 13:00:00+00:00,Warren Buffett's Berkshire Hathaway has been a fortress stock during recessions and bear markets. Here's how,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
7,0b93aaad46897662804d51438a1e9ae2,2023-02-17 20:30:12+00:00,Familiar Faces Powering Growth Stock Resurgence,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
8,0b94c9bf653f26e12a7496a3690e3102,2023-02-21 03:45:10+00:00,Major League Soccer and RBC Wealth Management Announce Multi-Year Partnership,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
9,0bc3b18faa9176599ab4853716f1a89e,2023-03-09 02:13:32+00:00,Apple and Foxconn efforts win labour reforms to advance Indian production plans - FT,relevant,relevant,relevant,relevant,relevant,relevant
10,0c3391057b0c60ea71c60b9b8fd5041f,2023-04-12 01:31:39+00:00,"Apple iPhone 15 Pro, iPhone 15 Pro Max Might Stick To Physical Instead Of Solid State Buttons",relevant,relevant,relevant,relevant,relevant,relevant
11,0c801db7bfec86758af4a398b4e5f6ea,2023-02-23 14:38:00+00:00,Unity Software stock slides nearly 20% as mobile-ad spending dries up and annual forecast weighs,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
12,0d8a07ec34e5a74e51c629a6a6bc15cd,2023-04-09 01:46:15+00:00,Social Livestreaming Platform Bigo Live Removed From App Store,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
13,0ddefb653e3efa7a727b88800303356b,2023-06-14 13:30:00+00:00,Sonos Era 300 Review: Spatial Audio Is a Game Changer,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
14,0e730430dfcaa2c5d25d9da668ab5fb3,2023-09-08 11:00:00+00:00,"Everything Apple Plans to Show on Sept. 12: iPhone 15, Watches, AirPods",relevant,relevant,relevant,relevant,relevant,relevant
15,0f36092460f98418237469867889c679,2023-06-12 12:43:00+00:00,Bank of America execs blew $93.6 billion. Here’s how they did it.,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
16,0f371483b1653d88d30c3582c6487d58,2023-09-12 21:21:45+00:00,Trading the Treasury Bond ETF (TLT) in Different Markets,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
17,100e3dffc56f6dd9994a34678be023df,2023-07-13 14:28:59+00:00,"For Long-Term EM Growth, India Answers the Bell",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
18,106ef80d70912444d47746f5600b0a2f,2023-05-09 01:20:04+00:00,This Popular Brand Has Better Profit Margins Than Apple or Nike. Is the Stock a Buy?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
19,10e98d0a5a8090025cb7112c3360c372,2023-01-12 04:26:17+00:00,"IDC, Gartner: 2022 PC Demand Dropped To Its ‘Lowest Level In Years’",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
20,11340d04835a63845d8c4cc0b074d880,2023-07-10 21:12:00+00:00,Apple executives fight subpoenas in shareholders' lawsuit against Qualcomm,relevant,relevant,relevant,relevant,relevant,relevant
21,139150980ca22a668ba81b71c40fed62,2023-01-18 04:26:55+00:00,Goldman Sachs Vs. Jefferies: Which Is the Better Investment?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
22,13cef80be1218f3732ac11dd61ff5ef6,2023-04-06 06:08:00+00:00,Apple says 'Hello Mumbai' at first India store launch,relevant,relevant,relevant,relevant,relevant,relevant
23,13fc3a810a81a75299c5feaabeb931f0,2023-10-03 20:33:02+00:00,What the Cheesecake Factory Effect means for malls,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
24,1461508b03972c7bc482e8f5ce3edc30,2023-01-25 04:08:33+00:00,Choice Hotels Opens Cambria Hotel Austin Uptown Near the Domain,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
25,14734bd08c2a1ff7f8706cc4b9d71179,2023-06-05 00:00:00+00:00,Introducing Apple Vision Pro: Apple’s first spatial computer,relevant,relevant,relevant,relevant,relevant,relevant
26,15566edbb46419b8685279b3ba44917d,2023-08-29 00:00:00+00:00,"Apellis to lay off 25% of staff, trim research in major restructuring",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
27,17b34ad7659f77c6683e2f2c0b6a4c3d,2023-04-16 13:39:48+00:00,"Tradr 2X Short TSLA Daily ETF (TSLQ) News, Articles, Events & Latest Updates",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
28,19854e66efe3da37574cdbd6d0bf1b5a,2023-08-29 22:24:18+00:00,Globalstar Names XCOM Labs Founder Paul Jacobs as CEO,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
29,1c1a0769d791b21fe9d6770a9f6f7971,2023-02-23 03:10:23+00:00,All 47 Warren Buffett Portfolio Stocks Now | Current 2023 Holdings List,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
30,1c9b525d2830c3d8a9ee642504b70253,2023-02-27 03:49:42+00:00,How Have the Top U.S. Asset Managers Voted in 2022?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
31,1d11bdf0752294e859320ee7463e9183,2023-03-19 18:23:00+00:00,Buffett's Berkshire Hathaway speeds up stock buybacks,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
32,1db4a5b0ba7245053e0d2d1414b9c8ac,2023-01-10 13:45:00+00:00,"Pepsi, Coke soda pricing targeted in new federal probe",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
33,1eecdc6b3173c480bc35e2f3e4a0b35a,2023-05-02 15:34:00+00:00,Apple fights $2 billion London lawsuit for 'throttling' millions of iPhones,relevant,relevant,relevant,relevant,relevant,relevant
34,1f88fb67c3b1932d1272e31bdd547226,2023-05-23 00:31:03+00:00,Apple announces multibillion-dollar deal with Broadcom for components made in the USA,relevant,relevant,relevant,relevant,relevant,relevant
35,21174edce3999a4750415c1d4a304921,2023-08-27 22:27:03+00:00,"Corporate America’s Chief Critic, Carl Icahn, Gets His Comeuppance (Published 2023)",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
36,2189304c5a62ee7040eb33dc70d5bc68,2023-04-13 04:06:00+00:00,Apple Triples India iPhone Output to $7 Billion in China Shift,relevant,relevant,relevant,relevant,relevant,relevant
37,21da9ed7d8cd239fbf60564837d0c0e5,2023-04-24 14:39:40+00:00,Eye on Tap to Pay: MagicCube Teams Up With ACI; Fiserv Offers Tap to Pay on Clover,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
38,21f04789fa15efceab5ae127c932b985,2023-01-05 03:59:02+00:00,Apple brings AI narration to audiobooks,relevant,relevant,relevant,relevant,relevant,relevant
39,226ff747507433c4aac9bed290eae3e0,2023-02-01 10:41:00+00:00,Spotify Reports Q4 2022 Earnings: Strong User Growth and Widened Losses,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
40,22c235ff3cf39b092c7ae10de8fbc311,2023-08-24 09:39:48+00:00,"Invesco S&P 500 Revenue ETF (RWL) Stock Price, Holdings, Dividend Yield",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
41,233131faf914c2f10e8a200a9c41a06a,2023-07-20 10:00:00+00:00,Netflix Strategic Changes Led to User Base Expansion & Record Revenues in Q2 2023,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
42,234e4ded26e54f7470e2633597a4a5cb,2023-02-06 03:03:59+00:00,NLRB: Apple illegally interfered with employees’ protected activity,relevant,relevant,relevant,relevant,relevant,relevant
43,24b66e0ef95e5444724de954df153a41,2023-06-01 08:15:00+00:00,Apple Bets On The Emerging Markets Growth Story,relevant,relevant,relevant,relevant,relevant,relevant
44,25241e59e12e525b1b39616915acab25,2023-01-13 03:59:02+00:00,Apple CEO Tim Cook to take a more than 40 percent pay cut,relevant,relevant,relevant,relevant,relevant,relevant
45,257205e81d7499c669c13242d4c75f28,2023-09-01 21:57:05+00:00,An Apple-leased building in Sunnyvale sold for $41M,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
46,25a7df0b943f559f15814d7963a9e04f,2023-07-13 23:07:08+00:00,Unlocking Business Potential with Apple’s Vision Pro,relevant,relevant,relevant,not relevant,relevant,relevant
47,2616a7040faba8f7cf1735f3675753e7,2023-01-23 05:49:00+00:00,7 Growth Stocks That Will Make You Rich in 10 Years,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
48,265261751676e6d007430a2f917bd1b7,2023-04-27 16:20:00+00:00,Webull expands to Japan,relevant,not relevant,not relevant,not relevant,not relevant,not relevant
49,2696a6fabdd2227a583d95b3cbb9505b,2023-06-28 00:26:42+00:00,Top 10 LGBT manufacturing leaders,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
50,2834d27797f52e2255ed228d073c6f0b,2023-05-25 15:20:00+00:00,Why Is Wearable Devices (WLDS) Stock Up 250%?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
51,287ab6d01f08405ed53c887fb31ce289,2023-05-08 01:05:40+00:00,CEO pay continues to soar – new study,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
52,297324e3a18c3ccc12b19c598dc31389,2023-07-13 15:33:08+00:00,"For Long-Term EM Growth, India Answers the Bell",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
53,2ab59f9aa8256dcc0598a2dda1f73372,2023-03-10 00:00:00+00:00,Apple Inc. to Launch Apple Music Classical App,relevant,relevant,relevant,relevant,relevant,relevant
54,2aeae2d7e50475da7923c0391af1353e,2023-02-28 14:40:41+00:00,Lightsource bp Places Multi-Year Order for 4GW of First Solar Modules,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
55,2b3d15fe000d8ff66ad19aa926097f84,2023-04-03 01:41:21+00:00,Garmin Forerunner 265 review: Brilliant but far too expensive,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
56,2b6ea8947a244e5416d5b3af525be227,2023-03-28 22:49:00+00:00,"Apple launches 'buy now, pay later' service in US",relevant,relevant,relevant,relevant,relevant,relevant
57,2c4041372820f815e3962f8ff5e932aa,2023-03-21 05:31:16+00:00,"For Broad-Based Large-Cap ESG Exposure, See CVLC",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
58,2f7c64f8924dcae8c787966ae6fe3ecd,2023-03-05 14:00:00+00:00,"Apple Readies Its Next Range of Macs, Including — Finally — a New iMac",relevant,relevant,relevant,relevant,relevant,relevant
59,2f862a180752ba0889801dbba8406de9,2023-02-11 03:32:43+00:00,Apple hires its first Chief People Officer in executive reshuffle,relevant,relevant,not relevant,not relevant,not relevant,not relevant
60,3088ea2a4ce82f61c5343f7504b3c423,2023-06-30 00:00:00+00:00,"Apple, world's most valuable public company, is first to hit $3 trillion in market value",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
61,30cfbe7ce698b889461a65234af2c669,2023-01-08 04:57:03+00:00,You might actually want a TiVo TV someday,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
62,3113be00474e3c309e02f243e8aef630,2023-08-29 19:30:41+00:00,Apple partner Globalstar taps former Qualcomm executive Paul Jacobs as CEO,relevant,relevant,relevant,not relevant,not relevant,not relevant
63,318fdef86daebe4911a736e33e38f310,2023-09-25 21:57:59+00:00,Uniqlo picks Tacoma Mall for its next Puget Sound-area store,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
64,3227431476c342f87aaf216d3eb63479,2023-09-23 22:11:00+00:00,T-Mobile CEO Sievert recalls the first iPhone launch on T-Mobile,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
65,33ef2d685867eaf0ab7fbb92ee1e9fa4,2023-08-31 13:36:00+00:00,Details on InvestigateTV+,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
66,34173776f440e91ff8510cad6d8baab8,2023-09-11 18:34:00+00:00,Qualcomm to supply Apple Inc with 5G chips until 2026 under new deal,relevant,relevant,relevant,relevant,relevant,relevant
67,3427e290809620aaa7947e3df02cf5ac,2023-10-30 20:31:00+00:00,"BlackBerry CEO Chen to retire, director Lynch to hold interim charge",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
68,343324b90fe33457b13355f1710a83f7,2023-02-22 08:53:00+00:00,Dexcom G6 Continuous Glucose Monitoring System Launches in Singapore,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
69,34acdfa4f332291b78c85e81f8072e47,2023-05-23 17:31:00+00:00,Apple inks multi-billion-dollar deal with Broadcom for U.S.-made chips,relevant,relevant,relevant,relevant,relevant,relevant
70,356bb215e901653432e0685762a4bf2e,2023-08-20 22:38:14+00:00,Nine million and counting: The controversial shopping app sweeping Australia,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
71,35e353d049c53919e19d677914520677,2023-08-17 22:51:17+00:00,WEBTOON is ready to take on Apple and Amazon (and win),not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
72,367b0436acb2607d7e62de5c5be72230,2023-05-03 22:16:00+00:00,Qualcomm outlook grim as smartphone sales stay weak,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
73,372996e774cae083609786817db4902a,2023-10-30 21:02:26+00:00,3 ETFs Setting the Gold Standard for Investor Returns,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
74,37aae86d64045d90cd2b9e0d05ae7174,2023-01-18 04:52:00+00:00,TSMC expects revenue to fall amid declining chip demand,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
75,3a1d78e4e343c560f73df5ce66b6ea40,2023-09-11 21:42:55+00:00,The hottest back-to-school accessory? A location sharing app,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
76,3bad1a0de0a31d5c5ae74ce15ecb996e,2023-01-23 06:27:00+00:00,How Apple’s Upcoming Mixed-Reality Headset Will Work,relevant,relevant,relevant,relevant,relevant,relevant
77,3bc87f76dd4dfe24a8033ec954b28196,2023-04-05 01:20:42+00:00,Apple and global suppliers expand renewable energy to 13.7 gigawatts,relevant,relevant,relevant,relevant,relevant,relevant
78,3c71b2a351c58facf42b62e6f98fe58e,2023-08-02 22:24:15+00:00,Garmin Fenix 7X Pro Solar Review | A new pinnacle in ultra-premium sports smartwatches,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
79,3fe4bdaf0d518ae9915cb00a3e218164,2023-03-09 02:55:24+00:00,Sonos Bets on Spatial Audio as a Key Brand Differentiator,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
80,40432721383ead647c027d058edb1448,2023-08-11 22:45:59+00:00,TechInsights Teardown: Apple iPhone 14 Plus,relevant,relevant,relevant,not relevant,not relevant,not relevant
81,4306f2073c42c430f39fdae61dadab39,2023-04-13 00:00:00+00:00,Apple will use 100 percent recycled cobalt in batteries by 2025,relevant,relevant,relevant,relevant,relevant,relevant
82,43728899c4ad37624d100bad06f115a8,2023-07-19 00:00:00+00:00,"Apple maintains its spot as the world’s most valuable brand, per Kantar BrandZ",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
83,43e0d7ae2b2ab8c35444efe7dd94173e,2023-06-09 16:59:00+00:00,"Apple, Amazon must face consumer lawsuit over iPhone, iPad prices, US judge rules",relevant,relevant,relevant,relevant,relevant,relevant
84,43f57bffaf4b56221b9e0a1a0ab95dd7,2023-05-12 10:00:00+00:00,Best Buy Announces New Membership Programs to Save You Money,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
85,44b5b3b2f43b4189b12837fc41d8b979,2023-09-11 07:35:00+00:00,"Qualcomm will make Apple’s iPhone modems until 2026, and its stock surges",relevant,relevant,relevant,relevant,not relevant,not relevant
86,45e90f89c1119fe0d617e73def865a55,2023-08-09 22:10:15+00:00,¿Eres cliente de Banco de Chile? Conoce cómo añadir tus tarjetas a Apple Pay,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
87,46d0fac49d7d7046e07c224eb86112c7,2023-10-11 05:22:00+00:00,Google CEO Pichai wrote to founders Page and Brin to decry bad ‘optics’ of search engine deal with Apple when he was in charge of Chrome,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
88,481e16cc2523effdbe9e490689036b4c,2023-02-27 03:10:23+00:00,"If I'd invested $1,000 in Berkshire Hathaway shares 25 years ago, here's how much I'd have now!",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
89,48218ec98a1e1404107b4be5011de4ce,2023-01-19 04:35:32+00:00,"Netflix’s Reed Hastings steps aside as co-CEO, stays on as executive chairman",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
90,48731c5f96a104e38d7860552024a612,2023-02-06 03:48:27+00:00,Sonos Is Having a Secret Sale Ahead of President's Day,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
91,487c0b7d08c2da7e5e0b43b1835bc905,2023-04-12 02:07:30+00:00,"TSMC’s Taiwan factory plans have not changed, says minister",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
92,48a61f984beea4bb47258e048aab5e6e,2023-01-31 04:04:01+00:00,Get Your Game on With Build-a-Bear's New 'Ted Lasso' Collection,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
93,4a7c54ae42773f820537973e69caf435,2023-01-11 04:57:25+00:00,Apple debuts free tool to help businesses get noticed,relevant,relevant,relevant,relevant,relevant,relevant
94,4a818bb4da41c004a39b0648cddf10b7,2023-10-12 21:10:38+00:00,United Promotes Benefits of Bluetooth Enabled Planes,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
95,4bb22c2b412f8bdc0d2fb3c8ea2dc68c,2023-07-11 06:02:00+00:00,Apple opens store on China's WeChat platform,relevant,relevant,relevant,relevant,relevant,relevant
96,4c7e7711c829e240ad5cdf08ba7ee669,2023-08-15 09:44:00+00:00,Ford taps Apple exec to build high-margin digital services,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
97,4f985bddc38d1a8dc7c766a9de9f9d09,2023-02-17 03:10:23+00:00,"UBS recommends its clients grab a full serving of Buffett's incredible, UNDERVALUED Berkshire Hathaway",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
98,50fee874da9908ccf335ffb80e324bc3,2023-09-11 21:35:55+00:00,Paul Jacobs Tapped to Lead Globalstar,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
99,51334516a61d5adae24588c63b0a135a,2023-02-03 03:32:49+00:00,Meta从虚拟元宇宙重回现实,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant

Titles whose classification changes with shot count: 16

shots,time_published,title
1,2023-01-10 04:03:16+00:00,Inari’s share price down over 4% as Apple plans to drop Broadcom chip from devices
46,2023-07-13 23:07:08+00:00,Unlocking Business Potential with Apple’s Vision Pro
48,2023-04-27 16:20:00+00:00,Webull expands to Japan
59,2023-02-11 03:32:43+00:00,Apple hires its first Chief People Officer in executive reshuffle
62,2023-08-29 19:30:41+00:00,Apple partner Globalstar taps former Qualcomm executive Paul Jacobs as CEO
80,2023-08-11 22:45:59+00:00,TechInsights Teardown: Apple iPhone 14 Plus
85,2023-09-11 07:35:00+00:00,"Qualcomm will make Apple’s iPhone modems until 2026, and its stock surges"
101,2023-02-23 18:04:00+00:00,Apple shareholder moves to boot Al Gore from board of directors
106,2023-10-24 15:25:43+00:00,FDA Clears Omnipod 5 App for iPhones
146,2023-09-01 15:18:00+00:00,Globalstar taps SpaceX to launch Apple's Emergency SOS satellites
153,2023-02-27 12:11:00+00:00,"Apple iPhone's Clean Energy Charging causes stir on social media over battery charging times, 'shaming'"
191,2023-01-11 04:03:16+00:00,Inari pares loss as analysts see limited impact from Apple's plan to drop Broadcom chip
211,2023-01-30 04:30:31+00:00,‘Acapulco’ Renewed for Season 3 at Apple
227,2023-02-21 03:48:27+00:00,Apple HomePod 2 vs Sonos One: is it worth paying more?
256,2023-01-21 04:57:44+00:00,予算3万円台の「スマートウォッチ」おすすめ5選 人気の「Apple Watch SE」から、コスパが良い高機能モデルまで【2023年1月版】 - Fav-Log by ITmedia
302,2023-04-27 01:49:47+00:00,"In Masimo v. Apple Trial Twist, Jurors Suddenly Learn Apple Hired Many Masimo Employees"

## How to judge whether few-shot prompting helped

First manually label this small fixed sample without looking at the model results. Then compare each shot-count column with those labels. A shift is not automatically an improvement: inspect whether the new label has a defensible direct ticker-specific mechanism in the headline. Keep the five demonstrations fixed while comparing shot counts; change and test them separately later if prompt wording or example selection becomes the next question.

## 3. Five-shot relevance filter: one pass over all AAPL headlines

In [34]:
FEW_SHOT_EXAMPLES = [
    {
        "date": "2023-01-03",
        "title": "Apple faces EU antitrust investigation over App Store practices",
        "label": "relevant",
    },
    {
        "date": "2023-01-04",
        "title": "Apple reports a sharp iPhone sales decline and cuts its revenue outlook",
        "label": "relevant",
    },
    {
        "date": "2023-01-05",
        "title": "Component supplier shares fall after reports that Apple may switch chip suppliers",
        "label": "not relevant",
    },
    {
        "date": "2023-01-06",
        "title": "Apple appoints a new Chief People Officer in an executive reshuffle",
        "label": "not relevant",
    },
    {
        "date": "2023-01-09",
        "title": "Apple TV+ renews a drama series for another season",
        "label": "not relevant",
    },
]


def format_example(example: dict) -> str:
    return (
        f"Publication date: {example['date']}\n"
        f"Headline: {example['title']}\n"
        f"Classification: {example['label']}"
    )

def build_relevance_prompt(ticker: str, published_at: pd.Timestamp, title: str, shots: int) -> str:
    assert 0 <= shots <= len(FEW_SHOT_EXAMPLES)
    examples = "\n\n".join(format_example(example) for example in FEW_SHOT_EXAMPLES[:shots])
    demonstrations = f"\n\nLABELLED EXAMPLES\n{examples}" if examples else ""
    return f"""You classify financial-news headlines for ticker {ticker}.

Classify a headline as relevant only when it describes a specific development
that could directly affect {ticker}'s revenue, demand, costs, supply chain,
products, strategy, financing, competitive position, or regulatory environment.
Classify it as not relevant when {ticker} is only in an ETF, index, stock list,
peer comparison, market roundup, investment recommendation, or generic sector
commentary without a direct company-specific mechanism.

Do not predict a return or use information outside the supplied date and headline.
Reply with exactly one label: relevant or not relevant.{demonstrations}

TARGET HEADLINE
Publication date: {published_at.date().isoformat()}
Headline: {title}
Classification:""".strip()

print(build_relevance_prompt(TICKER, article_sample.loc[0, "time_published"], article_sample.loc[0, "title"], shots=2))

You classify financial-news headlines for ticker AAPL.

Classify a headline as relevant only when it describes a specific development
that could directly affect AAPL's revenue, demand, costs, supply chain,
products, strategy, financing, competitive position, or regulatory environment.
Classify it as not relevant when AAPL is only in an ETF, index, stock list,
peer comparison, market roundup, investment recommendation, or generic sector
commentary without a direct company-specific mechanism.

Do not predict a return or use information outside the supplied date and headline.
Reply with exactly one label: relevant or not relevant.

LABELLED EXAMPLES
Publication date: 2023-01-03
Headline: Apple faces EU antitrust investigation over App Store practices
Classification: relevant

Publication date: 2023-01-04
Headline: Apple reports a sharp iPhone sales decline and cuts its revenue outlook
Classification: relevant

TARGET HEADLINE
Publication date: 2023-01-02
Headline: What is TSMC?
Classification:

In [35]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

assert torch.cuda.is_available(), "CUDA GPU required. Do not run this notebook on CPU."
assert HF_TOKEN, "HF_TOKEN is required to download the configured DeepSeek model."

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, token=HF_TOKEN)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    token=HF_TOKEN,
    torch_dtype="auto",
    device_map="auto",
).eval()

def generate_label(prompt: str) -> tuple[str | None, str]:
    messages = [{"role": "user", "content": prompt}]
    model_input = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    encoded = tokenizer(model_input, return_tensors="pt").to(model.device)
    with torch.inference_mode():
        generated = model.generate(
            **encoded,
            max_new_tokens=12,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )
    completion = tokenizer.decode(generated[0, encoded["input_ids"].shape[1]:], skip_special_tokens=True).strip()
    labels = re.findall(r"\bnot relevant\b|\brelevant\b", completion.lower())
    return (labels[-1] if labels else None), completion

records = []
for article in article_sample.itertuples(index=False):
    for shots in SHOT_COUNTS:
        prompt = build_relevance_prompt(TICKER, article.time_published, article.title, shots)
        label, raw_response = generate_label(prompt)
        records.append({
            "article_uid": article.article_uid,
            "time_published": article.time_published,
            "title": article.title,
            "shots": shots,
            "classification": label,
            "raw_response": raw_response,
        })

comparison_df = pd.DataFrame(records)
assert len(comparison_df) == len(article_sample) * len(SHOT_COUNTS)

Loading weights: 100%|██████████| 339/339 [00:03<00:00, 94.10it/s]

In [36]:

classification_table = (
    comparison_df
    .pivot(
        index=["article_uid", "time_published", "title"],
        columns="shots",
        values="classification",
    )
    .rename(columns=lambda shots: f"{shots}_shot")
    .reset_index()
)
display(classification_table)

changed_titles = classification_table.loc[
    classification_table.filter(regex=r"_shot$").nunique(axis=1, dropna=False).gt(1),
    ["time_published", "title"],
]
print(f"Titles whose classification changes with shot count: {len(changed_titles)}")
display(changed_titles)

shots,article_uid,time_published,title,0_shot,1_shot,2_shot,3_shot,4_shot,5_shot
0,01c4874dbb77a5c035d5bcea5fdd3ecc,2023-07-25 09:00:00+00:00,Introducing Norton Genie - Real-Time AI-powered Scam Detection at Your Fingertips,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
1,02bd82b62c7bf1d151a0808e2b11fbe3,2023-01-10 04:03:16+00:00,Inari’s share price down over 4% as Apple plans to drop Broadcom chip from devices,relevant,not relevant,not relevant,not relevant,not relevant,not relevant
2,03a1f810e8d95ea922887e8504ff2adb,2023-04-06 01:40:33+00:00,General Motors hates your iPhone,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
3,0447c69db0ac6b359d47220f1c08bc4f,2023-09-12 20:24:00+00:00,"Apple unveils iPhone 15 Pro with titanium case, holds line on prices",relevant,relevant,relevant,relevant,relevant,relevant
4,05bda0abee450c9248ea6a0d7f7dbd0d,2023-07-14 16:32:00+00:00,Apple Inc. stock underperforms Friday when compared to competitors despite daily gains,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
5,08838071f9f5ad5de8e609dfdd8c006d,2023-09-21 14:35:48+00:00,Expedia Group builds generative AI into multiple products in its “Fall Release”,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
6,09c0d12926b75d72091155728511af52,2023-05-05 13:00:00+00:00,Warren Buffett's Berkshire Hathaway has been a fortress stock during recessions and bear markets. Here's how,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
7,0b93aaad46897662804d51438a1e9ae2,2023-02-17 20:30:12+00:00,Familiar Faces Powering Growth Stock Resurgence,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
8,0b94c9bf653f26e12a7496a3690e3102,2023-02-21 03:45:10+00:00,Major League Soccer and RBC Wealth Management Announce Multi-Year Partnership,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
9,0bc3b18faa9176599ab4853716f1a89e,2023-03-09 02:13:32+00:00,Apple and Foxconn efforts win labour reforms to advance Indian production plans - FT,relevant,relevant,relevant,relevant,relevant,relevant
10,0c3391057b0c60ea71c60b9b8fd5041f,2023-04-12 01:31:39+00:00,"Apple iPhone 15 Pro, iPhone 15 Pro Max Might Stick To Physical Instead Of Solid State Buttons",relevant,relevant,relevant,relevant,relevant,relevant
11,0c801db7bfec86758af4a398b4e5f6ea,2023-02-23 14:38:00+00:00,Unity Software stock slides nearly 20% as mobile-ad spending dries up and annual forecast weighs,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
12,0d8a07ec34e5a74e51c629a6a6bc15cd,2023-04-09 01:46:15+00:00,Social Livestreaming Platform Bigo Live Removed From App Store,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
13,0ddefb653e3efa7a727b88800303356b,2023-06-14 13:30:00+00:00,Sonos Era 300 Review: Spatial Audio Is a Game Changer,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
14,0e730430dfcaa2c5d25d9da668ab5fb3,2023-09-08 11:00:00+00:00,"Everything Apple Plans to Show on Sept. 12: iPhone 15, Watches, AirPods",relevant,relevant,relevant,relevant,relevant,relevant
15,0f36092460f98418237469867889c679,2023-06-12 12:43:00+00:00,Bank of America execs blew $93.6 billion. Here’s how they did it.,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
16,0f371483b1653d88d30c3582c6487d58,2023-09-12 21:21:45+00:00,Trading the Treasury Bond ETF (TLT) in Different Markets,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
17,100e3dffc56f6dd9994a34678be023df,2023-07-13 14:28:59+00:00,"For Long-Term EM Growth, India Answers the Bell",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
18,106ef80d70912444d47746f5600b0a2f,2023-05-09 01:20:04+00:00,This Popular Brand Has Better Profit Margins Than Apple or Nike. Is the Stock a Buy?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
19,10e98d0a5a8090025cb7112c3360c372,2023-01-12 04:26:17+00:00,"IDC, Gartner: 2022 PC Demand Dropped To Its ‘Lowest Level In Years’",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
20,11340d04835a63845d8c4cc0b074d880,2023-07-10 21:12:00+00:00,Apple executives fight subpoenas in shareholders' lawsuit against Qualcomm,relevant,relevant,relevant,relevant,relevant,relevant
21,139150980ca22a668ba81b71c40fed62,2023-01-18 04:26:55+00:00,Goldman Sachs Vs. Jefferies: Which Is the Better Investment?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
22,13cef80be1218f3732ac11dd61ff5ef6,2023-04-06 06:08:00+00:00,Apple says 'Hello Mumbai' at first India store launch,relevant,relevant,relevant,relevant,relevant,relevant
23,13fc3a810a81a75299c5feaabeb931f0,2023-10-03 20:33:02+00:00,What the Cheesecake Factory Effect means for malls,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
24,1461508b03972c7bc482e8f5ce3edc30,2023-01-25 04:08:33+00:00,Choice Hotels Opens Cambria Hotel Austin Uptown Near the Domain,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
25,14734bd08c2a1ff7f8706cc4b9d71179,2023-06-05 00:00:00+00:00,Introducing Apple Vision Pro: Apple’s first spatial computer,relevant,relevant,relevant,relevant,relevant,relevant
26,15566edbb46419b8685279b3ba44917d,2023-08-29 00:00:00+00:00,"Apellis to lay off 25% of staff, trim research in major restructuring",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
27,17b34ad7659f77c6683e2f2c0b6a4c3d,2023-04-16 13:39:48+00:00,"Tradr 2X Short TSLA Daily ETF (TSLQ) News, Articles, Events & Latest Updates",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
28,19854e66efe3da37574cdbd6d0bf1b5a,2023-08-29 22:24:18+00:00,Globalstar Names XCOM Labs Founder Paul Jacobs as CEO,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
29,1c1a0769d791b21fe9d6770a9f6f7971,2023-02-23 03:10:23+00:00,All 47 Warren Buffett Portfolio Stocks Now | Current 2023 Holdings List,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
30,1c9b525d2830c3d8a9ee642504b70253,2023-02-27 03:49:42+00:00,How Have the Top U.S. Asset Managers Voted in 2022?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
31,1d11bdf0752294e859320ee7463e9183,2023-03-19 18:23:00+00:00,Buffett's Berkshire Hathaway speeds up stock buybacks,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
32,1db4a5b0ba7245053e0d2d1414b9c8ac,2023-01-10 13:45:00+00:00,"Pepsi, Coke soda pricing targeted in new federal probe",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
33,1eecdc6b3173c480bc35e2f3e4a0b35a,2023-05-02 15:34:00+00:00,Apple fights $2 billion London lawsuit for 'throttling' millions of iPhones,relevant,relevant,relevant,relevant,relevant,relevant
34,1f88fb67c3b1932d1272e31bdd547226,2023-05-23 00:31:03+00:00,Apple announces multibillion-dollar deal with Broadcom for components made in the USA,relevant,relevant,relevant,relevant,relevant,relevant
35,21174edce3999a4750415c1d4a304921,2023-08-27 22:27:03+00:00,"Corporate America’s Chief Critic, Carl Icahn, Gets His Comeuppance (Published 2023)",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
36,2189304c5a62ee7040eb33dc70d5bc68,2023-04-13 04:06:00+00:00,Apple Triples India iPhone Output to $7 Billion in China Shift,relevant,relevant,relevant,relevant,relevant,relevant
37,21da9ed7d8cd239fbf60564837d0c0e5,2023-04-24 14:39:40+00:00,Eye on Tap to Pay: MagicCube Teams Up With ACI; Fiserv Offers Tap to Pay on Clover,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
38,21f04789fa15efceab5ae127c932b985,2023-01-05 03:59:02+00:00,Apple brings AI narration to audiobooks,relevant,relevant,relevant,relevant,not relevant,not relevant
39,226ff747507433c4aac9bed290eae3e0,2023-02-01 10:41:00+00:00,Spotify Reports Q4 2022 Earnings: Strong User Growth and Widened Losses,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
40,22c235ff3cf39b092c7ae10de8fbc311,2023-08-24 09:39:48+00:00,"Invesco S&P 500 Revenue ETF (RWL) Stock Price, Holdings, Dividend Yield",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
41,233131faf914c2f10e8a200a9c41a06a,2023-07-20 10:00:00+00:00,Netflix Strategic Changes Led to User Base Expansion & Record Revenues in Q2 2023,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
42,234e4ded26e54f7470e2633597a4a5cb,2023-02-06 03:03:59+00:00,NLRB: Apple illegally interfered with employees’ protected activity,relevant,relevant,relevant,relevant,relevant,relevant
43,24b66e0ef95e5444724de954df153a41,2023-06-01 08:15:00+00:00,Apple Bets On The Emerging Markets Growth Story,relevant,relevant,relevant,relevant,relevant,relevant
44,25241e59e12e525b1b39616915acab25,2023-01-13 03:59:02+00:00,Apple CEO Tim Cook to take a more than 40 percent pay cut,relevant,relevant,not relevant,relevant,not relevant,not relevant
45,257205e81d7499c669c13242d4c75f28,2023-09-01 21:57:05+00:00,An Apple-leased building in Sunnyvale sold for $41M,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
46,25a7df0b943f559f15814d7963a9e04f,2023-07-13 23:07:08+00:00,Unlocking Business Potential with Apple’s Vision Pro,relevant,relevant,relevant,not relevant,not relevant,not relevant
47,2616a7040faba8f7cf1735f3675753e7,2023-01-23 05:49:00+00:00,7 Growth Stocks That Will Make You Rich in 10 Years,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
48,265261751676e6d007430a2f917bd1b7,2023-04-27 16:20:00+00:00,Webull expands to Japan,relevant,not relevant,not relevant,not relevant,not relevant,not relevant
49,2696a6fabdd2227a583d95b3cbb9505b,2023-06-28 00:26:42+00:00,Top 10 LGBT manufacturing leaders,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
50,2834d27797f52e2255ed228d073c6f0b,2023-05-25 15:20:00+00:00,Why Is Wearable Devices (WLDS) Stock Up 250%?,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
51,287ab6d01f08405ed53c887fb31ce289,2023-05-08 01:05:40+00:00,CEO pay continues to soar – new study,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
52,297324e3a18c3ccc12b19c598dc31389,2023-07-13 15:33:08+00:00,"For Long-Term EM Growth, India Answers the Bell",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
53,2ab59f9aa8256dcc0598a2dda1f73372,2023-03-10 00:00:00+00:00,Apple Inc. to Launch Apple Music Classical App,relevant,relevant,relevant,relevant,relevant,relevant
54,2aeae2d7e50475da7923c0391af1353e,2023-02-28 14:40:41+00:00,Lightsource bp Places Multi-Year Order for 4GW of First Solar Modules,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
55,2b3d15fe000d8ff66ad19aa926097f84,2023-04-03 01:41:21+00:00,Garmin Forerunner 265 review: Brilliant but far too expensive,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
56,2b6ea8947a244e5416d5b3af525be227,2023-03-28 22:49:00+00:00,"Apple launches 'buy now, pay later' service in US",relevant,relevant,relevant,relevant,relevant,relevant
57,2c4041372820f815e3962f8ff5e932aa,2023-03-21 05:31:16+00:00,"For Broad-Based Large-Cap ESG Exposure, See CVLC",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
58,2f7c64f8924dcae8c787966ae6fe3ecd,2023-03-05 14:00:00+00:00,"Apple Readies Its Next Range of Macs, Including — Finally — a New iMac",relevant,relevant,relevant,relevant,relevant,relevant
59,2f862a180752ba0889801dbba8406de9,2023-02-11 03:32:43+00:00,Apple hires its first Chief People Officer in executive reshuffle,relevant,relevant,not relevant,not relevant,not relevant,not relevant
60,3088ea2a4ce82f61c5343f7504b3c423,2023-06-30 00:00:00+00:00,"Apple, world's most valuable public company, is first to hit $3 trillion in market value",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
61,30cfbe7ce698b889461a65234af2c669,2023-01-08 04:57:03+00:00,You might actually want a TiVo TV someday,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
62,3113be00474e3c309e02f243e8aef630,2023-08-29 19:30:41+00:00,Apple partner Globalstar taps former Qualcomm executive Paul Jacobs as CEO,relevant,relevant,not relevant,not relevant,not relevant,not relevant
63,318fdef86daebe4911a736e33e38f310,2023-09-25 21:57:59+00:00,Uniqlo picks Tacoma Mall for its next Puget Sound-area store,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
64,3227431476c342f87aaf216d3eb63479,2023-09-23 22:11:00+00:00,T-Mobile CEO Sievert recalls the first iPhone launch on T-Mobile,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
65,33ef2d685867eaf0ab7fbb92ee1e9fa4,2023-08-31 13:36:00+00:00,Details on InvestigateTV+,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
66,34173776f440e91ff8510cad6d8baab8,2023-09-11 18:34:00+00:00,Qualcomm to supply Apple Inc with 5G chips until 2026 under new deal,relevant,relevant,relevant,relevant,relevant,relevant
67,3427e290809620aaa7947e3df02cf5ac,2023-10-30 20:31:00+00:00,"BlackBerry CEO Chen to retire, director Lynch to hold interim charge",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
68,343324b90fe33457b13355f1710a83f7,2023-02-22 08:53:00+00:00,Dexcom G6 Continuous Glucose Monitoring System Launches in Singapore,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
69,34acdfa4f332291b78c85e81f8072e47,2023-05-23 17:31:00+00:00,Apple inks multi-billion-dollar deal with Broadcom for U.S.-made chips,relevant,relevant,relevant,relevant,relevant,relevant
70,356bb215e901653432e0685762a4bf2e,2023-08-20 22:38:14+00:00,Nine million and counting: The controversial shopping app sweeping Australia,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
71,35e353d049c53919e19d677914520677,2023-08-17 22:51:17+00:00,WEBTOON is ready to take on Apple and Amazon (and win),not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
72,367b0436acb2607d7e62de5c5be72230,2023-05-03 22:16:00+00:00,Qualcomm outlook grim as smartphone sales stay weak,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
73,372996e774cae083609786817db4902a,2023-10-30 21:02:26+00:00,3 ETFs Setting the Gold Standard for Investor Returns,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
74,37aae86d64045d90cd2b9e0d05ae7174,2023-01-18 04:52:00+00:00,TSMC expects revenue to fall amid declining chip demand,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
75,3a1d78e4e343c560f73df5ce66b6ea40,2023-09-11 21:42:55+00:00,The hottest back-to-school accessory? A location sharing app,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
76,3bad1a0de0a31d5c5ae74ce15ecb996e,2023-01-23 06:27:00+00:00,How Apple’s Upcoming Mixed-Reality Headset Will Work,relevant,relevant,relevant,relevant,relevant,relevant
77,3bc87f76dd4dfe24a8033ec954b28196,2023-04-05 01:20:42+00:00,Apple and global suppliers expand renewable energy to 13.7 gigawatts,relevant,relevant,relevant,relevant,relevant,relevant
78,3c71b2a351c58facf42b62e6f98fe58e,2023-08-02 22:24:15+00:00,Garmin Fenix 7X Pro Solar Review | A new pinnacle in ultra-premium sports smartwatches,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
79,3fe4bdaf0d518ae9915cb00a3e218164,2023-03-09 02:55:24+00:00,Sonos Bets on Spatial Audio as a Key Brand Differentiator,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
80,40432721383ead647c027d058edb1448,2023-08-11 22:45:59+00:00,TechInsights Teardown: Apple iPhone 14 Plus,relevant,relevant,not relevant,not relevant,not relevant,not relevant
81,4306f2073c42c430f39fdae61dadab39,2023-04-13 00:00:00+00:00,Apple will use 100 percent recycled cobalt in batteries by 2025,relevant,relevant,relevant,relevant,relevant,relevant
82,43728899c4ad37624d100bad06f115a8,2023-07-19 00:00:00+00:00,"Apple maintains its spot as the world’s most valuable brand, per Kantar BrandZ",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
83,43e0d7ae2b2ab8c35444efe7dd94173e,2023-06-09 16:59:00+00:00,"Apple, Amazon must face consumer lawsuit over iPhone, iPad prices, US judge rules",relevant,relevant,relevant,relevant,relevant,relevant
84,43f57bffaf4b56221b9e0a1a0ab95dd7,2023-05-12 10:00:00+00:00,Best Buy Announces New Membership Programs to Save You Money,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
85,44b5b3b2f43b4189b12837fc41d8b979,2023-09-11 07:35:00+00:00,"Qualcomm will make Apple’s iPhone modems until 2026, and its stock surges",relevant,relevant,not relevant,not relevant,not relevant,not relevant
86,45e90f89c1119fe0d617e73def865a55,2023-08-09 22:10:15+00:00,¿Eres cliente de Banco de Chile? Conoce cómo añadir tus tarjetas a Apple Pay,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
87,46d0fac49d7d7046e07c224eb86112c7,2023-10-11 05:22:00+00:00,Google CEO Pichai wrote to founders Page and Brin to decry bad ‘optics’ of search engine deal with Apple when he was in charge of Chrome,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
88,481e16cc2523effdbe9e490689036b4c,2023-02-27 03:10:23+00:00,"If I'd invested $1,000 in Berkshire Hathaway shares 25 years ago, here's how much I'd have now!",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
89,48218ec98a1e1404107b4be5011de4ce,2023-01-19 04:35:32+00:00,"Netflix’s Reed Hastings steps aside as co-CEO, stays on as executive chairman",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
90,48731c5f96a104e38d7860552024a612,2023-02-06 03:48:27+00:00,Sonos Is Having a Secret Sale Ahead of President's Day,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
91,487c0b7d08c2da7e5e0b43b1835bc905,2023-04-12 02:07:30+00:00,"TSMC’s Taiwan factory plans have not changed, says minister",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
92,48a61f984beea4bb47258e048aab5e6e,2023-01-31 04:04:01+00:00,Get Your Game on With Build-a-Bear's New 'Ted Lasso' Collection,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
93,4a7c54ae42773f820537973e69caf435,2023-01-11 04:57:25+00:00,Apple debuts free tool to help businesses get noticed,relevant,relevant,relevant,relevant,not relevant,not relevant
94,4a818bb4da41c004a39b0648cddf10b7,2023-10-12 21:10:38+00:00,United Promotes Benefits of Bluetooth Enabled Planes,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
95,4bb22c2b412f8bdc0d2fb3c8ea2dc68c,2023-07-11 06:02:00+00:00,Apple opens store on China's WeChat platform,relevant,relevant,relevant,relevant,not relevant,not relevant
96,4c7e7711c829e240ad5cdf08ba7ee669,2023-08-15 09:44:00+00:00,Ford taps Apple exec to build high-margin digital services,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
97,4f985bddc38d1a8dc7c766a9de9f9d09,2023-02-17 03:10:23+00:00,"UBS recommends its clients grab a full serving of Buffett's incredible, UNDERVALUED Berkshire Hathaway",not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
98,50fee874da9908ccf335ffb80e324bc3,2023-09-11 21:35:55+00:00,Paul Jacobs Tapped to Lead Globalstar,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant
99,51334516a61d5adae24588c63b0a135a,2023-02-03 03:32:49+00:00,Meta从虚拟元宇宙重回现实,not relevant,not relevant,not relevant,not relevant,not relevant,not relevant

Titles whose classification changes with shot count: 31

shots,time_published,title
1,2023-01-10 04:03:16+00:00,Inari’s share price down over 4% as Apple plans to drop Broadcom chip from devices
38,2023-01-05 03:59:02+00:00,Apple brings AI narration to audiobooks
44,2023-01-13 03:59:02+00:00,Apple CEO Tim Cook to take a more than 40 percent pay cut
46,2023-07-13 23:07:08+00:00,Unlocking Business Potential with Apple’s Vision Pro
48,2023-04-27 16:20:00+00:00,Webull expands to Japan
59,2023-02-11 03:32:43+00:00,Apple hires its first Chief People Officer in executive reshuffle
62,2023-08-29 19:30:41+00:00,Apple partner Globalstar taps former Qualcomm executive Paul Jacobs as CEO
80,2023-08-11 22:45:59+00:00,TechInsights Teardown: Apple iPhone 14 Plus
85,2023-09-11 07:35:00+00:00,"Qualcomm will make Apple’s iPhone modems until 2026, and its stock surges"
93,2023-01-11 04:57:25+00:00,Apple debuts free tool to help businesses get noticed
95,2023-07-11 06:02:00+00:00,Apple opens store on China's WeChat platform
101,2023-02-23 18:04:00+00:00,Apple shareholder moves to boot Al Gore from board of directors
105,2023-01-11 12:38:00+00:00,Kuo doubles down on iPhone 15 Pro having no physical buttons
110,2023-08-17 00:00:00+00:00,Apple Card named Best Co-Branded Credit Card for Customer Satisfaction with No Annual Fee by J.D. Power
113,2023-03-12 10:59:00+00:00,"From Apple to Boeing, India is being put to the test as China manufacturing alternative"
137,2023-03-16 03:03:45+00:00,MLBN and Apple TV+ national broadcasts to show Zoom Replay Operations Center live under new deal
139,2023-01-13 03:59:02+00:00,Apple CEO Tim Cook to take more than 40% pay cut
144,2023-05-04 05:30:00+00:00,CEO Tim Cook says layoffs are a 'last resort' and not something Apple is considering right now
146,2023-09-01 15:18:00+00:00,Globalstar taps SpaceX to launch Apple's Emergency SOS satellites
153,2023-02-27 12:11:00+00:00,"Apple iPhone's Clean Energy Charging causes stir on social media over battery charging times, 'shaming'"
163,2023-01-11 04:31:49+00:00,Apple Watch patent infringement finding; Masimo seeks import ban
191,2023-01-11 04:03:16+00:00,Inari pares loss as analysts see limited impact from Apple's plan to drop Broadcom chip
192,2023-07-26 21:10:00+00:00,"Apple, Meta, Google argue they're not 'bookies' in casino app appeal"
219,2023-01-24 03:59:02+00:00,Apple builds on privacy commitment by unveiling new education and awareness efforts on Data Privacy Day
227,2023-02-21 03:48:27+00:00,Apple HomePod 2 vs Sonos One: is it worth paying more?
234,2023-08-30 00:00:00+00:00,Apple announces next Impact Accelerator class for businesses advancing environmental innovation
240,2023-01-06 04:31:08+00:00,Apple Analyst Says BOE Will Become Largest Display Supplier for iPhone 15
248,2023-08-02 18:51:00+00:00,Apple’s Goldman Sachs-Backed Savings Account Tops $10 Billion in Deposits
249,2023-09-14 14:40:00+00:00,Apple: Streamlining Sustainability For Every Buyer's Perfect Product
256,2023-01-21 04:57:44+00:00,予算3万円台の「スマートウォッチ」おすすめ5選 人気の「Apple Watch SE」から、コスパが良い高機能モデルまで【2023年1月版】 - Fav-Log by ITmedia
260,2023-02-02 03:03:59+00:00,Apple Is Dropping Industrial Design Chief Role in Post-Jony Ive Era

# 5-shot filtered news tone versus subsequent AAPL returns

This is a deliberately simple, forward-looking check. It keeps **only** headlines marked `relevant` by the 5-shot run, labels their likely company-news tone as positive, negative, or neutral once, then reuses that fixed news table for every price horizon. It tests whether majority positive/negative tone in non-overlapping 3- or 6-month news windows agrees with AAPL's forward return after 3, 5, 15, 20, 35, 45, or 90 trading days.

The return starts at the first trading-session close after the news window and ends exactly the stated number of trading days later: `(end close / start close - 1) × 100`. `actual_direction` is `up` for a positive return, `down` for a negative return, and `flat` for zero. This is an association check, not evidence that headlines cause or reliably predict returns.

In [ ]:
# Use only the existing five-shot relevance decisions; no vendor sentiment is used.
five_shot_relevant = (
    comparison_df.loc[
        comparison_df["shots"].eq(5) & comparison_df["classification"].eq("relevant"),
        ["article_uid", "time_published", "title"],
    ]
    .drop_duplicates("article_uid")
    .sort_values("time_published")
    .reset_index(drop=True)
)

def build_tone_prompt(ticker: str, published_at: pd.Timestamp, title: str) -> str:
    return f"""Classify the likely company-news tone of this relevant headline for {ticker}.

Use positive for a development likely favourable to the company, negative for a development likely unfavourable to the company, and neutral when the direction is unclear or balanced. Do not use later price movement or outside information.

Publication date: {published_at.date().isoformat()}
Headline: {title}
Tone (reply with exactly one label: positive, negative, or neutral):"""

def generate_tone(prompt: str) -> tuple[str | None, str]:
    messages = [{"role": "user", "content": prompt}]
    model_input = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    encoded = tokenizer(model_input, return_tensors="pt").to(model.device)
    with torch.inference_mode():
        generated = model.generate(
            **encoded, max_new_tokens=8, do_sample=False, pad_token_id=tokenizer.eos_token_id
        )
    completion = tokenizer.decode(
        generated[0, encoded["input_ids"].shape[1]:], skip_special_tokens=True
    ).strip()
    labels = re.findall(r"\bpositive\b|\bnegative\b|\bneutral\b", completion.lower())
    return (labels[-1] if labels else None), completion

tone_records = []
for article in five_shot_relevant.itertuples(index=False):
    tone, raw_tone_response = generate_tone(
        build_tone_prompt(TICKER, article.time_published, article.title)
    )
    tone_records.append({
        "article_uid": article.article_uid,
        "time_published": article.time_published,
        "title": article.title,
        "tone": tone,
        "raw_tone_response": raw_tone_response,
    })

five_shot_tone = pd.DataFrame(tone_records)
print({"five_shot_relevant_headlines": len(five_shot_tone), "tone_counts": five_shot_tone["tone"].value_counts(dropna=False).to_dict()})
display(five_shot_tone[["time_published", "title", "tone"]])

In [ ]:
import matplotlib.pyplot as plt

PRICE_REPO = "cookekieran/mag7_prices"
PRICE_FILENAME = "mag7_daily_prices.parquet"

price_path = Path(hf_hub_download(
    repo_id=PRICE_REPO, repo_type="dataset", filename=PRICE_FILENAME, token=HF_TOKEN
))
prices_raw = pd.read_parquet(price_path)

def find_column(frame: pd.DataFrame, candidates: set[str]) -> str:
    lookup = {str(column).strip().lower().replace(" ", "_"): column for column in frame.columns}
    match = next((lookup[name] for name in candidates if name in lookup), None)
    assert match is not None, f"Expected one of {sorted(candidates)}; found {list(frame.columns)}"
    return match

price_date_column = find_column(prices_raw, {"date", "timestamp", "datetime", "time"})
price_ticker_column = find_column(prices_raw, {"ticker", "symbol"})
price_close_column = find_column(prices_raw, {"adjusted_close", "adj_close", "close"})

aapl_prices = (
    prices_raw.loc[prices_raw[price_ticker_column].astype(str).str.upper().eq(TICKER)]
    .assign(date=lambda frame: pd.to_datetime(frame[price_date_column], utc=True).dt.tz_localize(None))
    .rename(columns={price_close_column: "close"})[["date", "close"]]
    .dropna()
    .drop_duplicates("date")
    .sort_values("date")
    .query("date >= '2023-01-01' and date <= '2026-12-31'")
    .reset_index(drop=True)
)
assert not aapl_prices.empty, "No AAPL prices were found in the configured price file."

monthly_price = aapl_prices.set_index("date")["close"].resample("ME").last()
fig, ax = plt.subplots(figsize=(12, 4))
monthly_price.plot(ax=ax, color="#1f77b4", linewidth=2)
ax.set(title="AAPL month-end close (2023--2026 available data)", xlabel="", ylabel="Close price")
ax.grid(axis="y", alpha=0.3)
plt.show()
print({"price_coverage": (str(aapl_prices["date"].min().date()), str(aapl_prices["date"].max().date())), "trading_days": len(aapl_prices)})

In [ ]:
# News is classified above exactly once. This cell only reuses five_shot_tone and price data.
MIN_DIRECTIONAL_ARTICLES = 5  # avoids calling a one-headline window "mainly" positive or negative
FORWARD_TRADING_DAYS = [3, 5, 15, 20, 35, 45, 90]
NEWS_WINDOW_MONTHS = [3, 6]
ANALYSIS_START = pd.Timestamp("2023-01-01")
ANALYSIS_END = pd.Timestamp("2026-06-01")

tone_for_windows = five_shot_tone.dropna(subset=["tone"]).copy()
tone_for_windows["month"] = tone_for_windows["time_published"].dt.tz_localize(None).dt.to_period("M").dt.to_timestamp()
price_dates = aapl_prices["date"].reset_index(drop=True)
price_closes = aapl_prices["close"].reset_index(drop=True)

def non_overlapping_windows(months: int):
    starts = pd.date_range(ANALYSIS_START, ANALYSIS_END, freq=pd.DateOffset(months=months))
    for start in starts:
        end = start + pd.DateOffset(months=months) - pd.Timedelta(days=1)
        if end <= ANALYSIS_END:
            yield start, end

def first_price_index_after(day: pd.Timestamp) -> int | None:
    positions = price_dates.index[price_dates.gt(day)]
    return None if len(positions) == 0 else int(positions[0])

def evaluate_window(months: int, window_start: pd.Timestamp, window_end: pd.Timestamp) -> list[dict]:
    in_window = tone_for_windows.loc[
        tone_for_windows["month"].between(window_start, window_end.to_period("M").to_timestamp())
    ]
    counts = in_window["tone"].value_counts()
    positive = int(counts.get("positive", 0))
    negative = int(counts.get("negative", 0))
    directional = positive + negative
    signal = (
        "bullish" if directional >= MIN_DIRECTIONAL_ARTICLES and positive > negative
        else "bearish" if directional >= MIN_DIRECTIONAL_ARTICLES and negative > positive
        else "mixed / insufficient"
    )

    # First close after the news window; h trading days ahead means close[t+h] / close[t] - 1.
    start_index = first_price_index_after(window_end)
    if start_index is None:
        return []

    rows = []
    for horizon_days in FORWARD_TRADING_DAYS:
        end_index = start_index + horizon_days
        if end_index >= len(price_dates):
            continue  # The future price period is not available yet.
        forward_return = price_closes.iloc[end_index] / price_closes.iloc[start_index] - 1
        actual_direction = "up" if forward_return > 0 else "down" if forward_return < 0 else "flat"
        rows.append({
            "news_window_months": months,
            "news_window": f"{window_start:%Y-%m-%d} to {window_end:%Y-%m-%d}",
            "positive": positive,
            "negative": negative,
            "neutral": int(counts.get("neutral", 0)),
            "news_signal": signal,
            "forward_trading_days": horizon_days,
            "return_period": f"{price_dates.iloc[start_index]:%Y-%m-%d} to {price_dates.iloc[end_index]:%Y-%m-%d}",
            "forward_return_pct": round(forward_return * 100, 2),
            "actual_direction": actual_direction,
            "direction_agrees": (signal == "bullish" and actual_direction == "up") or (signal == "bearish" and actual_direction == "down"),
        })
    return rows

trend_rows = []
for months in NEWS_WINDOW_MONTHS:
    for window_start, window_end in non_overlapping_windows(months):
        trend_rows.extend(evaluate_window(months, window_start, window_end))

trend_check = pd.DataFrame(trend_rows)
testable = trend_check.loc[trend_check["news_signal"].ne("mixed / insufficient")].copy()
agreement_summary = (
    testable.groupby(["news_window_months", "forward_trading_days"], as_index=False)
    .agg(windows_tested=("direction_agrees", "size"), agreement_rate_pct=("direction_agrees", "mean"))
    .assign(agreement_rate_pct=lambda frame: (frame["agreement_rate_pct"] * 100).round(1))
    .sort_values(["news_window_months", "forward_trading_days"])
)

display(trend_check)
display(agreement_summary)
print("Agreement rate is the percentage of testable news windows where bullish news preceded an up return or bearish news preceded a down return.")
print("The price-horizon loop does not call the LLM or re-parse articles.")